### ISSUE TITLE
Vapor new in existing directory

### ISSUE THREAD

**Issue by vdka** [vapor/toolbox#101]
If I run the following:

```
mkdir myApp
cd myApp
vapor new .
```

I get a `Package.swift` with `name: "."`.

This leads to a number of other issues. Special logic should be added for when the directory specified is `'.'` to default the project name to the name of the working directory

**Comment by tannernelson** [comment]
Why not just do:

```
vapor new myApp
cd myApp
```

**Comment by vdka** [comment]
I am a little too used to SwiftPM's `package init` I think, I tend to make the directory for the project first. The end result was just a lot of confusing error's, took me a little longer to work out than it should have.

**Comment by tannernelson** [comment]
Afaik SPM's method is the odd one out if you look at other framework CLI tools.
