### ISSUE TITLE
Staticly link the stdlib

### ISSUE THREAD

**Issue by vdka** [vapor/toolbox#102]
Just ran into `dyld: Symbol not found: __TMaCs17_AnyCollectionBox` when I ran `vapor self update`. I think this can be fixed by statically linking the stdlib. In the bash script use
`swift build -c release -Xswiftc -static-stdlib > /dev/null;`
It may not be all that useful now that the Swift3 transition is over, but still a good idea to have a binary that is as static as possible for tools

**Comment by LoganWright** [comment]
I think this one resolved itself 👍
