### ISSUE TITLE
vapor xcode - directory structure

### ISSUE THREAD

**Issue by zdenektopic** [vapor/toolbox#106]
Hello,

I have few issues with vapor toolbox.
1) `vapor xcode` command generates xcode project but flattens directory structure like this:
![snimek obrazovky 2016-10-26 v 17 17 11](https://cloud.githubusercontent.com/assets/2551911/19732127/10f6b2d6-9ba0-11e6-816a-98adebe404b0.png)
2) How do I update Vapor Framework to latest version? I did `swift package update`, `vapor self update` but it still reports:

> Vapor Toolbox v1.0.3
> Running online-assitant...
> Vapor Framework v1.0.2

**Comment by tannernelson** [comment]
1: That's an issue with SPM that they are working on.
2: Your `Package.swift` file is probably depending on `majorVersion: 1, minor: 0`. Bump the minor to `1`.
