### ISSUE TITLE
`vapor heroku push` fails with `Error: spawnProcess`

### ISSUE THREAD

**Issue by rsmoz** [vapor/toolbox#108]
`vapor heroku push` immediately fails with  `Error: spawnProcess`. This happens 100% of the time, on two different machines. Both run macOS 10.12.

**Comment by rsmoz** [comment]
whups, clicked the wrong button lol

**Comment by mdmathias** [comment]
Same for me.

**Comment by tannernelson** [comment]
@rsmoz how did you fix?

**Comment by rsmoz** [comment]
I didn't ¯\_(ツ)_/¯

**Comment by riklarkin** [comment]
me three

**Comment by tannernelson** [comment]
Pushing to the heroku branch of the GitHub project should work as a temporary workaround.

**Comment by tannernelson** [comment]
This should fix the issue: https://github.com/vapor/toolbox/pull/110

**Comment by timvermeulen** [comment]
I'm still having this issue, unfortunately.

**Comment by timrichardsn** [comment]
Ditto

**Comment by LoganWright** [comment]
Just for anyone finding this, here's the 


# Work Around

Just call this instead

```bash
git push heroku master
```

**Comment by dempseyatgithub** [comment]
FYI, I just hit this issue as well. And the workaround listed above worked for me.

**Comment by dniswhite** [comment]
was having the same issue and tried to above as well. it worked for me as well.

**Comment by OrRon** [comment]
same here

**Comment by tannernelson** [comment]
Looks to be fixed now: https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/HerokuPush.swift#L39
