### ISSUE TITLE
`vapor version` fails unless project is built from the command line

### ISSUE THREAD

**Issue by jjmanton** [vapor/toolbox#112]
This is low priority, but I did notice I am unable to print the vapor version unless I use `vapor build` in project. In my limited experience thus far, I have been using Xcode for build and test.

A little investigating showed that the tool is looking for the presence of the `.build` folder. An alternate solution might be to inspect Package.swift.

**Comment by tannernelson** [comment]
Inspecting the `Package.swift` file would unfortunately not include the patch or possibly even the minor versions.

A better solution might be to fetch the project and `cat` some version file that we add to the vapor framework.

**Comment by gperdomor** [comment]
also, the returned version is incorrect, I have  new project with vapor 1.3.8 and the `vapor version` command return:

```
Vapor Toolbox v1.0.3
Running sygnaler...
Vapor Framework v1.1.0
```

**Comment by vzsg** [comment]
The version `v1.1.0` is hardcoded in [Droplet.swift](https://github.com/vapor/vapor/blob/f384e07a778467f3c5af5ea770555a9508f749a3/Sources/Vapor/Droplet/Droplet.swift#L11), so it's unrelated to what the toolbox does. (It just calls the main application with the argument `version` anyway.)

**Comment by tannernelson** [comment]
@vzsg would be cool if we could do something like you did with the toolbox to keep that `VERSION` var upgraded. It's always tending to get forgotten.

**Comment by vzsg** [comment]
@tannernelson I agree, but right now I don't now how we could do anything of that sort here. The depencency packages are pulled in by SPM and there's no scripting support there (to my knowledge). Patching the sources in the local copy feels fragile.

**Comment by BrettRToomey** [comment]
Closing this for now. Feel free to reopen.
