### ISSUE TITLE
XCode (8C38) Segmentation fault 11 error

### ISSUE THREAD

**Issue by AZCoder2** [vapor/toolbox#115]
I've updated to the most current version of Vapor. When I import Vapor into a new source file, I get a "Command failed due to signal: Segmentation fault: 11 error on compilation" and it points to line 22 of Extractable.swift:

1.	While resolving type Extractable at [/Users/xxxxxxxx/Development/Error/Packages/Core-1.0.0/Sources/Core/Extractable.swift:22:11 - line:22:11] RangeText="E"
2.	While loading members for declaration 0x7fd41c232990 at <invalid loc>
3.	While deserializing 'validated' (FuncDecl #1085) 

My source file (called Friend.swift located in the Apps / Models folder) is nothing more than this:

`import Foundation`
`import Vapor`

The app DOES build properly from the command line.

**Comment by codesman** [comment]
@AZCoder2 Have you done `vapor clean && vapor xcode -y` and is the App Target selected in Xcode?

**Comment by AZCoder2** [comment]
Last question first - the App target has been selected each time.

I did NOT do a `vapor clean && vapor xcode -y`. Of course, the error is now wiped out. Clean build.

Since this is consistent, I presume there will be a bug fix sometime?

Thanks!
