### ISSUE TITLE
Executable not compiling in Ubuntu Sever 16.04 environment

### ISSUE THREAD

**Issue by proyb6** [vapor/toolbox#119]
For newly install Swift on some Linux servers, there are no mentioning on ```chown -R user:user /path/to/swift/folder``` to take an ownership, Vapor toolbar would failed silently and delete folder.

The toolbar should check ```stat -c %a swiftdirectory``` for 755/prompt user to check if they have ran command before running ```swift build -c release``` or exit if it hasn't have the full permission.

It works fine on Ubuntu Desktop.

**Comment by LoganWright** [comment]
@proyb6 does Swift officially support 16.04?

**Comment by proyb6** [comment]
Yes, the Swift 3 supported 16.04. I guess the extra step in chown can be done manually, this can be closed. Thanks.
