### ISSUE TITLE
Heroku Init may result in an incorrect Procfile

### ISSUE THREAD

**Issue by vzsg** [vapor/toolbox#123]
When `vapor heroku init` is run in a folder that already has a Procfile inside (for example after cloning the `basic-template` project), the toolbox blindly appends a new line at the end of the existing Procfile. This results in two `web` dyno definitions, which is invalid.

Fortunately for the user, in case of conflicts, Heroku will pick the last found configuration – so the project will ultimately build and run. But this is just a coincidence.

I think this situation could and should be avoided by checking if Procfile already exists, and telling the user about it, and giving him options to resolve.

Here are a few ideas about resolving the situation:
1. The command could avoid touching the existing Procfile completely, and instead print an informational message on how the `web` process should be declared.
1. The command could add a *commented out* `web` process to the Procfile with the expected declaration. (Lines that start with # are [ignored](http://stackoverflow.com/a/37083892/3952680) by Heroku.)
1. The command could ask the user about overwriting the Procfile (dangerous).
1. Or the command could parse the existing Procfile to check if there is a `web` process inside. If not, it can be inserted without bugging the user. If there is, the previous options could work, but with the `web` line being the unit of concern instead of the whole file.

**Comment by OrRon** [comment]
Great Ideas @vzsg 💪🏻
I believe it should work as described in the first option. If a Procfile exist it should print a warning with actionable data to inform the developer. Modifying it can be very dangerous and potentially frustrating to the developer.

**Comment by BrettRToomey** [comment]
Heroku will be/has been deprecated. Closing this for now.
