### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by makoni** [vapor/toolbox#126]
Is there a way to update to Toolbox 1.0.4 ? 

curl -sL toolbox.qutheory.io | bash and brew install vapor/tap/toolbox still installs 1.0.3

**Comment by vzsg** [comment]
If you use toolbox.qutheory.io, you are actually running the latest version.

The version number `1.0.3` is hardcoded in the sources, and it hasn't been updated before the 1.0.4 release unfortunately.
