### ISSUE TITLE
docker build gets stuck

### ISSUE THREAD

**Issue by aleffert** [vapor/toolbox#135]
When I use the automatically generated `Dockerfile` the build gets stuck on the `Install Swift Ubuntu 14.04 Snapshot` step. If I comment that part out the build succeeds. If I do `docker enter` and run the commands in that step manually it succeeds. If I replace `wget` with `curl -O` it succeeds.

This doesn't really make any sense, but in case anyone else had the same issue, the curl thing will fix it.

**Comment by beastgrim** [comment]
@aleffert  It's really bad thing. I have the same issue. But anyway I can't to build the image.
I wasted more than 2 days for it.
Do you now what problem in autogenerated Dockerfile?
When I try 'vapor docker build' it's takes forever!
If I comment part with '# Install Swift Ubuntu 14.04 Snapshot' vapor build image, but the image hasn't swift.

Can anybody give me example of Dockerfile that can successfully build with vapor?
Thanks!

**Comment by joscdk** [comment]
Docker in the vapor toolbox, is a bit outdated, i would suggest using the official Vapor docker repository to get Vapor working with Docker:
https://github.com/vapor/docker

**Comment by beastgrim** [comment]
@joscdk, thanks for the fastest response!

I have already tried this instructions. If I do 'docker run --rm -ti -v $(pwd):/vapor vapor/vapor:latest vapor build' I have error: 

```
/vapor/Packages/CSQLite-1.0.0/module.modulemap:2:12: error: header '/usr/include/sqlite3.h' not found
    header "/usr/include/sqlite3.h"
           ^
/vapor/Packages/SQLite-1.0.2/Sources/SQLite/SQLite.swift:2:12: error: could not build Objective-C module 'CSQLiteLinux'
    import CSQLiteLinux
```

So after that I tried copy repo to my app folder then go to the ' /docker/vapor' then do 'docker build -t vaporshop -build-arg INSTALL_SQLITE=true' and have error:

```
dev$ docker build -t vaporshop --build-arg INSTALL_SQLITE=true
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.
```

**Comment by joscdk** [comment]
Try:
`docker build -t vaporshop --build-arg INSTALL_SQLITE=true .`

**Comment by beastgrim** [comment]
@joscdk Thanks a lot, It works! ))

**Comment by joscdk** [comment]
No problem, closing issue :-)
