### ISSUE TITLE
Feature request: Running vapor xcode should but libraries in Sources/Libraries/

### ISSUE THREAD

**Issue by Antonasg** [vapor/toolbox#136]
Right now, when running ```vapor xcode ``` 
It puts all of the libraries in ```Sources/``` where the folder App also is.
See screenshot.
I think it would be nicer if they were put in ```Sources/Libraries/``` instead, getting a better overview.

<img width="240" alt="screen shot 2017-02-07 at 13 24 12" src="https://cloud.githubusercontent.com/assets/1011923/22691036/d04afd60-ed38-11e6-8c72-331f5a828411.png">

**Comment by Antonasg** [comment]
I guess this is actually related to https://github.com/vapor/toolbox/issues/106
But I'm not getting the same structure as zdenektopic.

**Comment by vzsg** [comment]
And just like with #106, this is beyond Vapor's control.
SPM will eventually generate a nicer-to-read folder structure.
