### ISSUE TITLE
support swift 3.1

### ISSUE THREAD

**Issue by tanner0101** [vapor/toolbox#138]
The compatibility check scripts and `.build` folder changes need to be supported for Swift 3.1.

We will also need to change the ordering of `-Xswiftc` args

```
swift package -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib generate-xcodeproj
```

**Comment by hzyyy** [comment]
any ideas when this is coming?

**Comment by BrettRToomey** [comment]
Fixed.
