### ISSUE TITLE
"Error: fileOrDirectoryNotFound" on "vapor heroku init command" (possibly related to issue #104)

### ISSUE THREAD

**Issue by MarkKroll** [vapor/toolbox#144]
I am new to Vapor, Heroku and Swift, but the command _vapor heroku init_ used to work just fine a couple days ago. However, I noticed that there is now a new question prompt:

`Would you like to deploy to other than US region server?
y/n>`

After inputting either 'y' or 'n', I consistently receive the same result:
`Error: fileOrDirectoryNotFound`

The command sequence execution is aborted prematurely, and the program returns back to the MacOS terminal prompt.

This kinda of shuts down my learning progress :) ... Is it just my problem? Is there a workaround?

PS. After some googling I found this issue: #104 "Added ability to choose deployment region for new Heroku apps", which has recently been merged to production, I think. Perhaps there is a glitch with the code someplace, but I am definitely not knowledgable enough to find out what this might be.

Thanks for any help... ! Vapor rocks!

**Comment by vzsg** [comment]
While the issue is being investigated, there is a workaround: you can create the Heroku application manually.

Follow these steps:

1. Create a git repository for your application with `git init`.
1. Verify that you have a Procfile in your project.(*)
1. Commit your initial state.
```
# git add .
# git commit -m "Add initial project"  
```
4. Create the application with the Heroku CLI.  
Replace `your-app-name` and the `us` region (`eu` is the other option) as you like.

```
# heroku apps:create your-app-name --region us --buildpack https://github.com/vapor/heroku-buildpack.git 
```

5. Push your repo.

```
# git push heroku master
```

---

(*) Note that I assumed that you created your project using the `basic-template` (the one you get by executing `vapor new`). That template already contains a working Procfile. If you started elsewhere, copy [this Procfile](https://github.com/vapor/basic-template/blob/master/Procfile) into the root of your repo.

**Comment by MarkKroll** [comment]
@vzsg thank you so much for your quick reply to this issue. Much appreciated! However, when I run the following command:
`heroku apps:create TodoServe --region us --buildpack https://github.com/vapor/heroku-buildpack.git`

I get this output:
`Creating ⬢ TodoServe... !
 ▸    Name must start with a letter and can only contain lowercase letters, numbers, and
 ▸    dashes.`

Am I still doing something wrong? Please let me know if you need any additional information from me, e.g. logs (if any), my system setup etc. I'm not sure if mine is an isolated case, or is this repeatable by other users.

(*) Your `basic-template` assumption is correct, I am only beginning to discover Vapor, so I'm not even familiar with the concept of templates (not yet). But I'm learning....

**Comment by MarkKroll** [comment]
Also... in case this might be useful, in regard to step 2, in your instructions above: I do have Procfile in my project root directory with this content:

`web: App --env=production --workdir="./"`

**Comment by vzsg** [comment]
The error message is actually quite exact: the application name cannot be "TodoServe", because it must be all lowercase. Call it "todoserve" instead (though that name might not be available).

**Comment by MarkKroll** [comment]
Wow! Sorry for not carefully reading the feedback messages. My bad. (Although I must say, this is a very restrictive naming convention requirement. You don't come across such as this one too often. )

Anyway, it works! Thanks again for your super-fast support.

**Comment by vzsg** [comment]
It may sound strict, but if you consider that this will be the URL of your application (`todoserve.herokuapp.com`), it starts making sense. 😉

**Comment by MarkKroll** [comment]
Here's what I got by querying my system setup:
* Vapor Toolbox v1.0.6
* Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1), Target: x86_64-apple-macosx10.9
* heroku-cli/5.6.31-6c22097 (darwin-amd64) go1.7.5

Anything else, I'll be happy to provide.

**Comment by MarkKroll** [comment]
Also, I run zsh on my terminal (although that is probably irrelevant):
* zsh 5.2 (x86_64-apple-darwin16.0)

**Comment by MarkKroll** [comment]
@vzsg, based on my prior blooper of not knowing the proper url naming convention scheme, I ran another quick test on my system. I thought that perhaps upper case characters might be causing problems. So, this time, everything in the new test project was lower-cased, as prescribed by the url naming convention scheme.

However, the issue still remains. Here's a small screenshot from my terminal window:

<img width="537" alt="screen shot 2017-03-10 at 9 36 16 am" src="https://cloud.githubusercontent.com/assets/14081303/23806251/cf0b50a8-0575-11e7-994a-47e46f31602f.png">

**Comment by vzsg** [comment]
Alright, I have reproduced the issue. Thank you for the input, I'll see if I can fix it too.

**Comment by MarkKroll** [comment]
Excellent. Glad to be of help. :thumbsup:
