### ISSUE TITLE
CLibreSSl Module Map could not be added during build

### ISSUE THREAD

**Issue by bmontegani** [vapor/toolbox#151]
Ubuntu 16.04
Swift 3.1
vapor toolbox v 1.0.8
vapor framework v1.1.0

basic hello project (no changes)
`vapor new hello`

```
vapor build
Fetching Dependencies [Done]
Could not add CLibreSSL Module Map: fileOrDirectoryNotFound
Building Project [Done]
```

**Comment by TimC-BBC** [comment]
@bmontegani This is a known issue and not actually an error when using Vapor 1, so nothing to worry about. You can silence this warning with a `--modulemap` flag in your `vapor new` command.

As an aside, the Vapor Framework v1.1.0 is another bug in the toolbox, unless your `Package.swift` is pointing to `Major: 1, Minor: 1`

**Comment by 0xTim** [comment]
@bmontegani This is a known issue and not actually an error when using Vapor 1, so nothing to worry about. You can silence this warning with a --modulemap flag in your vapor new command.

As an aside, the Vapor Framework v1.1.0 is another bug in the toolbox, unless your Package.swift is pointing to Major: 1, Minor: 1

**Comment by tanner0101** [comment]
this is fixed in the latest toolbox build.

**Comment by fabrijp** [comment]
I have found that if you move your project folder to another directory you may have a issue with CLibreSSL unbrella header file that have the path hard coded on the file "module.modulemap" under GeneratedModuleMap/CLibreSSL. Updating the path fixed it for me.
