### ISSUE TITLE
Toolbox on Ubuntu 16.04 armhf doesn't install

### ISSUE THREAD

**Issue by darthpelo** [vapor/toolbox#158]
Hi, since the curl -sL toolbox.vapor.sh | bash is deprecated, it's not more possibile to install and use Vapor with Ubuntu 16.04 armhf (Raspberry Pi boards for example).

I tried with the quick script and manual, following the instructions: http://beta.docs.vapor.codes/getting-started/install-on-ubuntu/#apt-repo.

In both cases `sudo apt-get update` returns this error:
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://repo.vapor.codes/apt xenial InRelease' doesn't support architecture 'armhf'

Of course sudo apt-get install vapor fails because apt-get cannot finds vapor package.

Is it possible to add the ARM support to the repository? Or reactivate the old toolbox.vapor.sh script?

Thanks

**Comment by tanner0101** [comment]
@darthpelo for these situations i'd recommend compiling the toolbox yourself (which is what the old script used to do).

```
git clone git@github.com:vapor/toolbox.git
cd toolbox
swift build -c release
mv .build/release/Executable /usr/local/bin/vapor
```

I'll add these instructions to the readme

**Comment by tanner0101** [comment]
https://github.com/vapor/toolbox/commit/23762a4f26fa124ab0f5318b2ba19e3e78f578f6

**Comment by darthpelo** [comment]
@tanner0101 thanks!

**Comment by jjnino** [comment]
@tanner0101 I am trying with the instructions above but I get the following:

error: Failed to clone git@github.com/vapor-cloud/clients.git to <AsolutePath: "<homedir>/toolbox/.build/repositories/clients.git-1389065760">

any idea?

**Comment by vzsg** [comment]
It exists, but that repo is unfortunately not public. :( You need to check out an older tag, for example `git checkout tags/2.0.3` that didn't have support for Vapor Cloud yet.

@tanner0101 It would be really nice, if either this repo could become public, or there was a compile time flag for _enabling_ Cloud support including in Package.swift – so you can build the full version in-house, but the repo also works for everyone else.

**Comment by jjnino** [comment]
@vzsg Thanks for the help! I was able to build. Too bad it is an older tag!

**Comment by tanner0101** [comment]
just publicized it. sorry about that!
