### ISSUE TITLE
Heroku init fails if user has fresh installation of heroku cli tool

### ISSUE THREAD

**Issue by plummer** [vapor/toolbox#159]
If the user has a fresh copy of the heroku cli, for example from homebrew with:

`brew install heroku`

When the code reaches:

```
let url: String
  do {
    url = try console.backgroundExecute(program: "heroku", arguments: ["create", name, "--region", region])
  console.info(url)
  } catch ConsoleError.backgroundExecute(_, let message, _) {
    throw ToolboxError.general("Unable to create Heroku app: \(message.trim())")
  }
```

the heroku tool is stuck asking the user for credentials, and the `vapor heroku init` script hangs silently.

Workaround: run the heroku cli tool separately and input credentials.

Ideal outcome: The script fails and instructs the user to input credentials separately.

This really only impacts brand new users, however they are the most likely to get stuck here.

**Comment by BrettRToomey** [comment]
Heroku support will be/has been deprecated. Closing for now.
