### ISSUE TITLE
Vapor build error with toolbox 2 and vapor 1.* project

### ISSUE THREAD

**Issue by mludi** [vapor/toolbox#162]
Hi, on a Vapor 1 project is a build error with toolbox 2 beta.

On my machine I'm running
Vapor Toolbox: 2.0.0-beta.2
Vapor Framework: 1.5.15

So with 

`vapor build -Xswiftc -I/usr/local/bin/mysql -Xlinker -L/usr/local/bin/mysql`

or

`vapor build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/bin`

I got the error

```
Output:
Compile Swift Module 'App' (30 sources)
Linking ./.build/debug/App
ld: library not found for -lmysqlclient for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

For a temporary fix the SPM helps

`swift build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib`

**Comment by hhanesand** [comment]
I don't think Vapor 1.x is compatible with Toolbox 2.x...

I could be wrong, but does going back to Toolbox 1.x fix your problem?

**Comment by mludi** [comment]
That will work but it's a known bug

**Comment by tanner0101** [comment]
Please use this for the time being (thanks @mludi):

```sh
swift build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib
```

We're working on a solution for the next update.

**Comment by tanner0101** [comment]
Closing this since we are about to tag Toolbox 2.0.
