### ISSUE TITLE
Support generating Provider templates

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/toolbox#165]
It would be great if I could generate a Provider template for Vapor using command like so:
```
vapor new MYProvider --type=provider
```

This would beneficial for the Vapor community and would help accelerate the growth of Providers/Plugins development in the Vapor Ecosystem

**Comment by BrettRToomey** [comment]
I agree with the general principle. Although, instead of types, I think we can get away with adding an official provider template and just do `vapor new MyProvider --template=provider`

**Comment by kdawgwilk** [comment]
I started a [template here](https://github.com/kdawgwilk/provider-template) but not sure if I am doing things right

**Comment by tanner0101** [comment]
@kdawgwilk what you have there looks great. I'd add one example configurable item like https://github.com/vapor/leaf-provider/blob/master/Sources/LeafProvider/Provider.swift#L24. In a lot of the examples in the docs i mention a custom logger protocol called `AllCapsLogger` that does `.uppercase()` on a string before printing. http://beta.docs.vapor.codes/vapor/droplet/#example
Perhaps we could include an implementation of this logger that this provider adds using `addConfigurable` in `boot(config:)`.

**Comment by kdawgwilk** [comment]
Does toolbox have a built in find & replace after it clones down the template?  I tried to use the same name `ProviderTemplate` everywhere that would need to be replaced with the users provider name.

**Comment by tanner0101** [comment]
Hmmm it doesn't right now but that seems like it would be really useful for all types of templates. I'll create a separate issue for that.

**Comment by tanner0101** [comment]
Closing this here since the toolbox supports loading any template. Leaving https://github.com/vapor/toolbox/issues/167 open for a future version to make templating providers easier.
