### ISSUE TITLE
[BETA] Unable to create Xcode Project if project does not build

### ISSUE THREAD

**Issue by 0xTim** [vapor/toolbox#166]
When creating a new project (unable to verify if it occurs on existing projects at the moment), if your project does not build - for example after having updated to a new version of Vapor that contains breaking changes - `vapor xcode` will always fail as it attempts to build the project rather than generating the Xcode project and letting Xcode build it. The workaround is to run `swift package generate-xcodeproj`

**Comment by BrettRToomey** [comment]
It attempts to build it? What? Really?

**Comment by BrettRToomey** [comment]
Oh, wow. It actually does ([for reference](https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/Xcode.swift#L21)). I think this can be fixed in toolbox by using `swift package update` instead. I'm not sure of any limitations. @tanner0101 @LoganWright

**Comment by tanner0101** [comment]
This was an understanding. @LoganWright fixed in 1.0.9
