### ISSUE TITLE
Git initialization issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by davidvpe** [vapor/toolbox#168]
I installed Vapor Toolbox on Ubuntu 16.04 and the installation was successful. Although when I create a new project and it tries to initialize the git repo, terminal throws an error

`davidvpe@UbuntuVirtual:~/Escritorio$ vapor new Test`
`Cloning Template [Done]`
`Updating Package Name [Done]`
`Initializing git repository [Failed]`
`could not initialize git repository`

Host: Ubuntu 16.04
Vapor Toolbox: 1.0.9

**Comment by tanner0101** [comment]
Fixed in https://github.com/vapor/toolbox/pull/169
