### ISSUE TITLE
Documentation for vapor cli

### ISSUE THREAD

**Issue by brunobl** [vapor/toolbox#178]
Unless I'm mistaken, there's no real documentation for vapor cli.

When typing "vapor" only (or at least vapor help), all commands should be displayed.
I discovered for example about vapor run routes on slack, but there doesn't seem to be a way to directly discover about it (except typing something like "vapor run garbage" to display help)

**Comment by tanner0101** [comment]
Thanks for reporting. Information about how to access help for application commands has been added here: https://github.com/vapor/documentation/commit/ca574786efc74f3091acdca912836e9f0a6a5d1e
