### ISSUE TITLE
brew update: Error: No such file or directory - vapor1

### ISSUE THREAD

**Issue by muescha** [vapor/toolbox#182]
with brew upgrade i get an error:

```
$ brew outdated
vapor/tap/toolbox (1.0.7) < 1.0.9

$ brew upgrade
==> Upgrading 1 outdated package, with result:
vapor/tap/toolbox 1.0.9
==> Upgrading vapor/tap/toolbox 
==> Downloading https://github.com/vapor/toolbox/releases/download/1.0.9/macOS-sierra
Already downloaded: /Users/muescha/Library/Caches/Homebrew/toolbox-1.0.9
==> mv macOS-sierra vapor
Error: No such file or directory - vapor1
```

**Comment by vzsg** [comment]
I'm not sure about this issue, but the homebrew formula was renamed to "vapor" – that might cause trouble. Try uninstalling `toolbox` (with `--force` if necessary), then installing `vapor/tap/vapor` for the v2 toolbox, and/or `vapor/tap/vapor1` for the v1 toolbox, if you still work with legacy projects.

**Comment by tanner0101** [comment]
I think @vzsg is right. Homebrew probably doesn't like the name being swapped out from under it.

@muescha try doing a force uninstall:

```sh
brew uninstall vapor --force
brew uninstall vapor1 --froce
```

then reinstall normally. should work.

please reopen if it continues to fail. thanks!

**Comment by muescha** [comment]
i think it comes from this line:

`bin.install "vapor1`
https://github.com/vapor/homebrew-tap/blob/master/toolbox.rb#L11

**Comment by muescha** [comment]
@tanner0101 can you confirm this wrong line?

**Comment by muescha** [comment]
(btw: force uninstalling and reinstall i get version 2.0.3 and no error)
