### ISSUE TITLE
Can not install vapor toolbox according to documentation

### ISSUE THREAD

**Issue by alex-ross** [vapor/toolbox#186]
Tried to install the toolbox using

```
$ curl -sL toolbox.vapor.sh | bash
```

Nothing happends and when using just `curl toolbox.vapor.sh` i get `curl: (6) Could not resolve host: toolbox.vapor.sh`.

**Comment by joscdk** [comment]
Hi @alex-ross 

You should install the Toolbox through homebrew on Mac.
https://docs.vapor.codes/2.0/getting-started/install-on-macos/#add-homebrew-tap

**Comment by alex-ross** [comment]
@joscdk ok, thanks. Somehow I must have found an old documentation then.
The homebrew solution did work great :)
