### ISSUE TITLE
[beta] load file fails

### ISSUE THREAD

**Issue by tanner0101** [vapor/toolbox#188]
```
Gertrude:website tanner$ vapor-beta cloud deploy
Git detected, to manually choose an application use the --app option.
Could not load tokens: Data File Error: unable to load file at path /Users/tanner/.vapor/token.json

Identifier: Core.DataFileError.load

Here are some possible causes: 
- file doesn't exist
- missing read permissions at specified path
- data read is corrupted
- system issue

These suggestions could address the issue: 
- ensure that file permissions are correct for specified paths

Vapor's documentation talks about this: 
- https://developer.apple.com/reference/foundation/filemanager
No user currently logged in.
Login: vapor cloud login
Sign up: vapor cloud signup
Error: Login required
Gertrude:website tanner$ 
```

**Comment by nhatlee** [comment]
Hi @tanner0101 I got the same error on `vapor 2.0` swift 4. Here is the logs:
`[Data File Error: unable to load file at path /Users/nhatlee/MyWebsite/Resources/Views/welcome] [Identifier: Core.DataFileError.load] [Possible Causes: file doesn't exist, missing read permissions at specified path, data read is corrupted, system issue] [Suggested Fixes: ensure that file permissions are correct for specified paths] [Documentation Links: https://developer.apple.com/reference/foundation/filemanager]`. How to fix it?

**Comment by tanner0101** [comment]
That looks like an error with Vapor, not the toolbox. Have you correctly registered and chosen the leaf provider? (I ask because the welcome view is not correctly being suffixed with `.leaf`)

**Comment by nhatlee** [comment]
Hi @tanner0101 here is the image of the error when I run get method. I just add a simple `.leaf` (html content) file as you can see in the image.
<img width="1381" alt="screen shot 2017-09-26 at 9 05 39 am" src="https://user-images.githubusercontent.com/7148482/30839202-891e8106-a29a-11e7-9803-bf9a57eac3e9.png">
And my Package:
`.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 2),
        .Package(url: "https://github.com/vapor/fluent-provider.git", majorVersion: 1),
        .Package(url: "https://github.com/vapor-community/postgresql-provider.git", majorVersion: 2),
        .Package(url: "https://github.com/vapor/leaf.git", majorVersion: 2),
        .Package(url: "https://github.com/vapor/leaf-provider.git", majorVersion: 1)`

**Comment by tanner0101** [comment]
Could be that you have not properly configured the Leaf provider. Try following the instructions here: https://docs.vapor.codes/2.0/leaf/provider/

**Comment by nhatlee** [comment]
I following the docs but it seem out of date. I got the error `Value of type 'Droplet' has no member 'viewsDir'`

**Comment by vzsg** [comment]
Ignore the Manual step. (It's indeed outdated, but completely unnecessary too.)

Concentrate on configuring the service in droplet.json instead.

**Comment by nhatlee** [comment]
Hi @vzsg and @tanner0101 I still got the same error after added config:
`[Data File Error: unable to load file at path /Users/nhatlee/MyWebsite/Resources/Views/welcome.leaf] [Identifier: Core.DataFileError.load] [Possible Causes: file doesn't exist, missing read permissions at specified path, data read is corrupted, system issue] [Suggested Fixes: ensure that file permissions are correct for specified paths] [Documentation Links: https://developer.apple.com/reference/foundation/filemanager]`
Here is my config:
`let config = try Config()
try config.setup()
try config.addProvider(LeafProvider.Provider.self)

let drop = try Droplet(config)
try drop.setup()

try drop.run()`
And also added `"view": "leaf",` to `droplet.json`

**Comment by vzsg** [comment]
I see two problems:
1. Change `welcome.leaf` to `welcome` [at this line](https://github.com/nhatlee/MyWebsite-SwiftVapor/blob/master/Sources/App/Routes.swift#L39).
1. The view itself is in the wrong folder. Right know, it is under Sources/Views, but it should be Resources/Views instead. Move the file out and it should start working.

**Comment by nhatlee** [comment]
@vzsg Thanks so much for your support. Now it's work properly.

**Comment by tbegeberg** [comment]
It worked for me to remove the .leaf from welcome and in routes just call "welcome".
