### ISSUE TITLE
Toolbox 3.0.1 is not compiled with static stdlib

### ISSUE THREAD

**Issue by vzsg** [vapor/toolbox#194]
The currently available version of the toolbox binary is dynamically linked to the Swift libraries. This results in broken installations on any system where Xcode 9 is not installed at `/Applications/Xcode.app`. For example, see vapor/documentation#225.

To resolve this, the a new build should be published, where the `-Xswiftc -static-stdlib` flag is passed to the build command.

---

Note that swift build's `--static-swift-stdlib` flag is currently broken, as noted in Xcode 9's r[elease notes](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html). This might have caused the current mess.

> Known Issues
> Creating static executables using the new option --static-swift-stdlib does not function correctly. (33861492)
> Workaround: Build the package using the following command: swift build -Xswiftc -static-stdlib.

**Comment by tanner0101** [comment]
Related to #195

**Comment by tanner0101** [comment]
Fixed: https://github.com/vapor/toolbox/releases/tag/3.0.2
Thanks, vzsg!
