### ISSUE TITLE
`vapor update --xcode` does not recognize `--xcode` option

### ISSUE THREAD

**Issue by marc-medley** [vapor/toolbox#197]
**Error**

The command `vapor update --xcode` returns "Error: Could not generate Xcode project: error: unknown option --xcode;"

```
macos> vapor update --xcode
Updating [Done]
Changes to dependencies usually require Xcode to be regenerated.
Would you like to regenerate your xcode project now?
y/n> y
Generating Xcode Project [Failed]
error: unknown option --xcode; use --help to list available options

Error: Could not generate Xcode project: error: unknown option --xcode; 
use --help to list available options
```

**Checked Help**

However, `vapor update --help` does state that `--xcode` is a valid option

```
macos> vapor update --help
Usage: vapor update [--xcode] 

Updates your dependencies.

Arugments:

Options:
  xcode Removes any Xcode projects while cleaning. 
```

**Expected Behavior**

1. Expected to *not* be prompted with "Would you like to regenerate your xcode project now?"
2. Expected `--xcode` to be recognized
3. Expected xcode project to be regerenated non-interactively.

**Version Information**

```
macos> brew info vapor
vapor/tap/vapor: stable 3.0.2
https://vapor.codes
/usr/local/Cellar/vapor/3.0.2 (4 files, 16.7MB) *
  Built from source on 2017-10-09 at 12:06:32
From: https://github.com/vapor/homebrew-tap/blob/master/vapor.rb
==> Dependencies
Required: ctls ✔
```

**Comment by tanner0101** [comment]
looks like that flag is erroneously included in the `--help` output. `vapor update` automatically asks to regenerate xcode projects for a while now.
