### ISSUE TITLE
Add command line arguments to Xcode build scheme on `vapor xcode` executed

### ISSUE THREAD

**Issue by NathanFlurry** [vapor/toolbox#20]
## Add command line arguments to Xcode build scheme on `vapor xcode` executed

* Author(s): [NathanFlurry](https://github.com/nathanflurry)

## Introduction

This feature would allow for the correct port and workDir to be set when generating Xcode projects.

## Motivation

When running a Vapor application from Xcode, the wording directory is not the same as if running it from the command line. Because of this, the app can't find files properly using the default working directory in Xcode.

## Proposed solution

To fix this, I propose that when `vapor xcode` is executed, it automatically updates the build scheme to add the flags `--config:app.port=8080 --workDir=$(SRCROOT)`.

## Code snippets

I don't know too much about how `.xcodeproj` files are structured, but from what I can tell, the CLI would have to edit the file `VaporApp.xcodeproj/xcuserdata/<username>.xcuserdatad/xcschemes/App.xcscheme` and add this under the proper launch action:
```xml
<CommandLineArguments>
   <CommandLineArgument
      argument = "--config:app.port=8080"
      isEnabled = "YES">
   </CommandLineArgument>
   <CommandLineArgument
      argument = "--workDir=$(SRCROOT)"
      isEnabled = "YES">
   </CommandLineArgument>
</CommandLineArguments>
```

## Impact

This will simply make it easier for people to get up and running with new projects without any errors.

## Alternatives considered

Not adding it at all, but it saves a lot of time by doing this.

**Comment by tannernelson** [comment]
I think this is a great idea. I'd love to see it implemented.

**Comment by LoganWright** [comment]
Definitely want this, would need to see what it takes to edit those files safely.

**Comment by tannernelson** [comment]
This is approved.

**Comment by feinstruktur** [comment]
I’ve a quick look at the file structure.

This might be easier to do once we’ve split up the CLI into bits and use SPM to build it, because then we can pull in an XML lib or at least avoid piling XML parsing into the main file as well.

Unless we just do a “brute force” insertion between `</BuildableProductRunnable>\n<CommandLineArguments>`, which works I guess but is brittle in case the input changes order etc.

**Comment by tannernelson** [comment]
We know the exact version of Xcode and that it's a new project being generated by this command, so I think we could make a hack that would work for now without XML parsing.

**Comment by NathanFlurry** [comment]
Actually, it might be better to simply put this in a config file. To do that, we should also add custom variables to values defined in the config files, e.g. the default config file would be `{ "work-dir": "{{SRCROOT}}" }` (assuming that `workDir` will eventually become a config variable).

**Comment by LoganWright** [comment]
@NathanFlurry the one weird thing about `workDir` in the config is that we need the `workDir` to know where to look for the `Config/` directory, so you get into a weird situation of where to look for it. 

On the `{{SRCROOT}}`, we could maybe look at the file, but that's often different than the source root, depending if the file is nested in subdirectories. The xcode project's env var `$(SRCROOT)` is a convenient way to get the root directory of the project.

I like the idea about not needing to mess w/ XcodeProj files.

Maybe looking into the file location is good enough. We could even make it smart enough to search around the directories of the file location to see if we can get other info.

**Comment by eneko** [comment]
Was this fixed at some point already? Or does `swift package generate-xcodeproj` solve this problem? I am using Xcode with Vapor 0.17 and seems to find all config files properly.

**Comment by NathanFlurry** [comment]
I don't feel there is a need for this because of the method being used right now to analyze the working directory from the `#file` value. If users want to add a `--workDir` flag manually, they are welcome to.
