### ISSUE TITLE
Build on Ubuntu 16.10 with Swift 4

### ISSUE THREAD

**Issue by TofPlay** [vapor/toolbox#200]
Hi,
All my services are defined as Docker image with Ubuntu 16.10. 
On the services I run Vapor 2 with Swift 3.1
I would like to migrate them to Swift 4 (on Ubuntu 16.10)
On Ubuntu 16.10 only Swift 3.1 is available. To migrate I create an image with Ubuntu 16.10 and Swift 4 downloaded and install from Swift.org
Now to build `toolbox` I use your old `bootstrap.sh`:
```
#!/bin/bash
curl -sL "check.vapor.sh" | bash || exit 1;

DIR=".vapor-toolbox-temporary";

rm -rf $DIR;

mkdir -p $DIR
cd $DIR;

echo "⬇️  Downloading...";
git clone https://github.com/vapor/toolbox vapor-toolbox;
cd vapor-toolbox;

TAG=$(git describe --tags);
git checkout $TAG > /dev/null 2>&1;

cat Sources/Executable/main.swift | \
    awk -v tag="$TAG" '/let version = "master"/ { printf "let version = \"%s\"\n", tag; next } 1' > .tmp && \
    mv .tmp Sources/Executable/main.swift;

echo "🛠  Compiling...";
swift build -c release;

echo "🚀  Installing...";
.build/release/Executable self install;

cd ../../;
rm -rf $DIR;

echo 'Use vapor --help and vapor <command> --help to learn more.';
```
When I execute `bootstrap.sh` I have this output:
```
root@68e8725c1968:/projects/toolbox# ./bootstrap.sh
✅  Compatible with Vapor 2
⬇️  Downloading...
Cloning into 'vapor-toolbox'...
remote: Counting objects: 4163, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 4163 (delta 28), reused 38 (delta 21), pack-reused 4111
Receiving objects: 100% (4163/4163), 18.52 MiB | 615.00 KiB/s, done.
Resolving deltas: 100% (2424/2424), done.
Checking connectivity... done.
🛠  Compiling...
lsb_release -r
which clang
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/3 -lPackageDescription -swift-version 3 -I /usr/lib/swift/pm/3 -sdk / /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/Package.swift -fileno 5
Fetching git@github.com:vapor-cloud/clients.git
Fetching https://github.com/vapor/console.git
git clone --mirror https://github.com/vapor/console.git /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/console.git-7484835740698826026
Fetching https://github.com/vapor/vapor.git
git clone --mirror https://github.com/vapor/vapor.git /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/vapor.git--4189435503055573360
Fetching https://github.com/vapor/redis.git
Fetching https://github.com/vapor/json.git
git clone --mirror git@github.com:vapor-cloud/clients.git /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/clients.git-1303307639408449565
git clone --mirror https://github.com/vapor/redis.git /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/redis.git--7408628345938410555
git clone --mirror https://github.com/vapor/json.git /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/json.git-702892651879148636
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/json.git-702892651879148636 rev-parse --is-bare-repository
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/json.git-702892651879148636 tag -l
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/redis.git--7408628345938410555 rev-parse --is-bare-repository
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/redis.git--7408628345938410555 tag -l
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/vapor.git--4189435503055573360 rev-parse --is-bare-repository
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/vapor.git--4189435503055573360 tag -l
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/console.git-7484835740698826026 rev-parse --is-bare-repository
git -C /projects/toolbox/.vapor-toolbox-temporary/vapor-toolbox/.build/repositories/console.git-7484835740698826026 tag -l
```
I do not have an error but it does not build toolbox
Is there a tutorial that explains how to build Vapor from scratch?

**Comment by tanner0101** [comment]
Could you build it using our APT instead? That is the preferred method. Will be much faster as well since you don't have to compile it.

https://docs.vapor.codes/2.0/getting-started/toolbox/#apt

**Comment by TofPlay** [comment]
No I can not because the apt version for Ubuntu 16.10 install Swift 3.1 not Swift 4

**Comment by tanner0101** [comment]
oh, we should update that then. /cc @joscdk

**Comment by TofPlay** [comment]
Let me know when is done 🙂

**Comment by joscdk** [comment]
Swift 4 is now available for 16.10 .. Next release of the toolbox will as well be available for Swift 4 on 16.10

But just a side note, it's always recommended to use Ubuntu LTS versions, in this case 16.04 to make sure to get updates, packages work etc. :)

**Comment by TofPlay** [comment]
@joscdk first thanks release of the toolbox on Ubuntu 16.10 with Swift 4. I understand you point but all my services are build on Ubuntu 16.10. We will not downgrade to 16.04 now, too much work and tests.

**Comment by TofPlay** [comment]
@tanner0101, @joscdk  just for my information I'm interested to know how you build toolbox. I have a project in my mind to run vapor on others distributions like [Alpine Linux](https://www.alpinelinux.org/about/). If I understand how you do it on Ubuntu it could help me to adapt the process to another distribution.

**Comment by vzsg** [comment]
You shouldn't exercise that thought so much. Swift heavily builds on glibc, and will not work on Alpine's musl libc (nor with uclibc).

**Comment by TofPlay** [comment]
@vzsg I know about glibc. 😕 But I would love to build embedded solutions with Swift and Vapor. 😄
 Ubuntu is ok for services on servers but not the best distribution for embedded solutions. 😔

**Comment by futurejones** [comment]
I to would like some documentation on how to build the vapor toolbox. I am working with swift 4.1 on arm64/aarch64 devices and need to build the toolbox on the device.
