### ISSUE TITLE
cleanup beta db command

### ISSUE THREAD

**Issue by tanner0101** [vapor/toolbox#202]
- [x] use console loading bar animations while waiting for redis responses
- [x] improve formatting of output for multiple environments during create. looks like info is duplicated at first.
- [x] allow user to select token from a list if not supplied 

PR: https://github.com/vapor/toolbox/pull/203

**Comment by joscdk** [comment]
Released in 3.1.2 https://github.com/vapor/toolbox/releases/tag/3.1.2

**Comment by joscdk** [comment]
Released in `3.1.2`
