### ISSUE TITLE
Current release of toolbox source can't build because of vapor-cloud access

### ISSUE THREAD

**Issue by ckd** [vapor/toolbox#205]
See subject 😄 

@tanner0101

**Comment by joscdk** [comment]
@tanner0101 we should maybe consider looking through, and open sourcing the clients and models repos, that should be the only Cloud repositories used by the toolbox

**Comment by vzsg** [comment]
As I noted under another issue, an alternative solution would be using a compile time flag to _enable_ Cloud functionality through the source (including Package.swift). So mortals can build a cloudless build, and you can build the full version inhouse, using the same source.

**Comment by tanner0101** [comment]
Fixed.
