### ISSUE TITLE
increment next major version by some arbitrary number to cut down on framework version confusion

### ISSUE THREAD

**Issue by tanner0101** [vapor/toolbox#212]
We should consider tagging the next toolbox version (4) as 14 or 9 or something. Tons of people get the toolbox version confused with Vapor framework version making for a lot of wasted time in #help.

**Comment by calebkleveter** [comment]
What if we tag it 3.14 and append an additional digit of Pi every time there is a new release?

**Comment by vzsg** [comment]
For a command line tool (as opposed to a library you _link against_), there's not much point in semantic versioning to begin with. Even a build timestamp can serve the purpose.

**Comment by tanner0101** [comment]
@vzsg do you recommend any specific formats for that?  Maybe just `YYMMDD`?

**Comment by 0xTim** [comment]
How does Homebrew and APT handle non semantic-versioned requirements? (At least not in the format x.y.z)

**Comment by joscdk** [comment]
At least APT would need semantic version .. But to decouple at least APT from GitHub version might be beneficial, and then maybe have the git hash as part of the version

**Comment by tanner0101** [comment]
`YYMMDD` would be parsed as a major version without minor or path. And it follows that each new version would be `>` the previous one. So there's no problem w/ that format at least. 

@joscdk do you know about APT?

**Comment by joscdk** [comment]
APT will need at least x.y.z but as said above, decoupling from GitHub version might be a good idea, to make it easier to version based on Swift version :) and then just show git hash in the version, so people know which commit it relates to :)
