### ISSUE TITLE
Empty heroku repository breaks vapor update

### ISSUE THREAD

**Issue by leo150** [vapor/toolbox#215]
**Context**
swift 4.0.3
vapor toolbox 3.0.1, 3.1.4
git 2.14.3 (Apple Git-98)
empty repository on heroku
<details><summary>Package.swift</summary><p>

```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
  name: "Bot",
  products: [
    .executable(name: "LevBot", targets: ["LevBot"]),
    ],
  dependencies: [
    .package(url: "https://github.com/leo150/Pelican.git", .branch("develop")),
    .package(url: "https://github.com/vapor/fluent-provider.git", .upToNextMajor(from: "1.2.0")),
    .package(url: "https://github.com/vapor-community/postgresql-provider.git", .upToNextMajor(from: "2.1.0"))
  ],
  targets: [
    .target(name: "LevBot",
        dependencies: [
          "Pelican",
          "FluentProvider",
          "PostgreSQLProvider"
        ],
        path: "Sources")
  ]
)
```
</p></details> <br />

**Trying**
 ```shell
$ vapor update
```

**Got**
>Error: backgroundExecute(code: 128, error: "fatal: ambiguous argument \'heroku/master...master\': unknown revision or path not in the working tree.\nUse \'--\' to separate paths from revisions, like this:\n\'git <command> [<revision>...] -- [<file>...]\'\n", output: "")

**Possible solution**
 ```shell
$ git remote remove heroku
$ vapor update
Updating [Done]
<...>
```
However, adding remote back breaks `update` again.
 ```shell
$ git remote add heroku <correct heroku url>
$ vapor update
Error: backgroundExecute <...>
```

**Comment by axello** [comment]
Weird, I have the same bug, but I'm not on heroku but on gitlab as a remote origin. When I do a 
`mv .git .git2` and try `vapor build` again, I get the following output:
```
Error: backgroundExecute(code: 1, error: "warning: \'fetch\' command is deprecated; use \'resolve\' instead\n/Users/axel/github/artwhisper-server2: error: manifest parse error(s):\n/Users/axel/github/artwhisper-server2/Package.swift:3:22: error: incorrect argument label in call (have \'name:products:targets:dependencies:\', expected \'name:pkgConfig:targets:dependencies:\')\nlet package = Package(\n                     ^\n", output: "")
```

The  package.swift file was copied from a new vapor project, where it works flawlessly. 
I already remove .build, xcodeproject etc. to no avail.

Really weird bug.

**Comment by vzsg** [comment]
The original error is thrown by [this line](https://github.com/vapor/toolbox/blob/3.1.6/Sources/VaporToolbox/Update.swift#L22) in Update.swift, whose purpose is a complete mystery to me. For a command that should do nothing else than call `swift package update`, this is an unnecessary point of failure. Maybe it could be eliminated. What do you think, @tanner0101?

**Comment by axello** [comment]
A workaround for now, is to use `swift package update` and `swift package generate-xcodeproj` instead of using the broken wrapper, according to @vzsg
