### ISSUE TITLE
ld: library not found for -lssl after `vapor update`

### ISSUE THREAD

**Issue by vinamelody** [vapor/toolbox#217]
Hi, I was trying to fix an issue by doing `vapor update` but then Xcode build keeps failing with `ld: library not found for -lssl. 

<img width="1149" alt="screen shot 2018-03-26 at 10 04 24 pm" src="https://user-images.githubusercontent.com/990511/37911147-d6f89052-3141-11e8-8e5c-58e8d37ef53d.png">

I tried regenerating using `rm -rf .build/ *.xcodeproj/ Package.resolved && vapor xcode -y` but it's not working.

Discarding changes in `Package.resolved` also does not fix the entire project :(

```
Vapor Toolbox: 3.1.4
Vapor Framework: 3.0.0-rc.2.2
```
Please help, thanks!

**Comment by 0xTim** [comment]
@vinamelody you either need to upgrade vapor toolbox (`brew upgrade vapor`) or install LibreSSL `brew install libressl`

**Comment by vinamelody** [comment]
woot, thanks @0xTim .. you're here and there at RW too 🥇  will wait for the gist
