### ISSUE TITLE
Terminal state is incorrect if pinentry is invoked to sign the initial commit during "vapor new"

### ISSUE THREAD

**Issue by interstateone** [vapor/toolbox#222]
**Setup:**

My ~/.gitconfig contains the following in order to sign commits:
```
[commit]
    gpgSign = true
```

GPG is installed with brew, and is using pinentry-curses to prompt for my private key passphrase when signing a commit.

**Steps to reproduce:**

Run `vapor new NAME` writes to the terminal correctly up until pinentry-curses is invoked, at which point the terminal state is incorrect. I've recorded what this looks like, although pinentry's prompt is outside of the recorded area. If I interrupt vapor the terminal state is still broken and I need to `killall pinentry` from another shell. The behaviour is the same whether or not I'm inside of tmux, and the recording is not within tmux.

![small](https://user-images.githubusercontent.com/594059/39086397-d3391340-454d-11e8-8840-2d00864abeb6.gif)

**Expected behaviour:**

I would expect that vapor would allow pinentry to finish running so that I can enter my passphrase before attempting to continue its own work, and throughout the process the terminal state is correct.

**Comment by tanner0101** [comment]
This is now working in the latest version
