### ISSUE TITLE
vapor run serve Error with fileOrDirectoryNotFound

### ISSUE THREAD

**Issue by zerozheng** [vapor/toolbox#225]
I build a new project, and run `vapor run serve`, but get a error `Error: fileOrDirectoryNotFound`.

system: ubuntu 16.04.

the output of `vapor run --help` is:

```
$ vapor run --help

Usage: vapor run [--exec]
Runs the compiled application.
Arguments:
Options:
     --exec The executable name.
```

Is there something wrong i do?  

THANKS FOR YOUR HELP

**Comment by zerozheng** [comment]
I got it, after rebuild the project, it works

**Comment by dym-sh** [comment]
also likely: just forgot to `vapor xcode` before `vapor build`
