### ISSUE TITLE
Allow deleting a domain

### ISSUE THREAD

**Issue by natanrolnik** [vapor/toolbox#232]
Currently, with the toolbox, it is only possible to create, but not delete, domains associated with an app.
(Besides that, is it possible to delete a domain in the cloud dashboard?)

**Comment by joscdk** [comment]
Yeah it is unfortunately a missing feature, we don't have the API for it. It is actually not a very missed feature, but it will be part of the new Toolbox that will integrate against our new Cloud 2 API :)
