### ISSUE TITLE
git error on `vapor update -y` when working on local branch

### ISSUE THREAD

**Issue by sebastianfrelle** [vapor/toolbox#234]
I was working on a local feature branch titled `feature/email-integration`, which I *hadn't* pushed to my remote, `origin`. I have another remote, `heroku`. I ran `vapor update -y` and saw the following error:

```
$ vapor update -y
Error: backgroundExecute(code: 128, error: "fatal: ambiguous argument \'origin/feature/email-integration...feature/email-integration\': unknown revision or path not in the working tree.\nUse \'--\' to separate paths from revisions, like this:\n\'git <command> [<revision>...] -- [<file>...]\'\n", output: "")
```

**Comment by calebkleveter** [comment]
For some reason that I am un-aware of, you have to have the branch you are on pushed to origin to be able to install/updated your dependencies. This is a Swift Package Manager thing, and not Toolbox, so there isn't much we can do about it. Maybe if you dig around [their repo](https://github.com/apple/swift-package-manager) you will find something.

**Comment by vzsg** [comment]
That's not true, this is entirely is a toolbox thing. [This check](https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/Update.swift#L22) fails when the current branch is not pushed, but there are no comments or any sane explanation available why it's there.

Especially considering that a regular `swift package update` works even in this scenario (and has been my recommended workaround).

**Comment by sebastianfrelle** [comment]
Judging from [`checkGitUpstream()`](https://github.com/vapor/toolbox/blob/dde859a446ef9014f5e6a2bcc91d4975eac67bf9/Sources/VaporToolbox/Update.swift#L50), it looks like the call to [`gitInfo.verify(local:remote:)`](https://github.com/vapor/toolbox/blob/dde859a446ef9014f5e6a2bcc91d4975eac67bf9/Sources/VaporToolbox/Update.swift#L64) might throw an error.

I just can't seem to figure out where `verify(local:remote:)` is defined-- otherwise, I might have submitted a pull request myself.

**Comment by grundoon** [comment]
@sebastianfrelle Just FYI, it's defined here https://github.com/vapor/toolbox/blob/8dcdca82dd4fcfc9fad2abf5ace64fde6a4576f2/Sources/Cloud/Commands/Deploy.swift#L213

**Comment by vzsg** [comment]
@LoganWright I see you're updating the toolbox, do you think [this stuff](https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/Update.swift#L39-L69) could be eliminated for good before making a new release?
