### ISSUE TITLE
Building Vapor Toolbox halts on dependency having git protocol

### ISSUE THREAD

**Issue by segabor** [vapor/toolbox#236]
I'm currently trying to build toolbox on Arch Linux but package update silently halts because one of the dependency packages is specified with git protocol.
```swift
        // Vapor Cloud clients.
        .Package(url: "git@github.com:vapor-cloud/clients.git", majorVersion: 0),
```
If I replace it with https it goes on a while but stops again the next dependency
```
Fetching git@github.com:vapor-cloud/models.git
```

So how can I build my own vapor toolbox without kindly asking you to assign my public key to vapor projects?

**Comment by segabor** [comment]
I'm not exactly following you. The dependency URL we are talking about is git prefixed indicating it requires an SSH key to authenticate which I don't have. Yes if I fix that particular URL to use https it will work until the next dependency with git protocol specified.

I can fix the former url because it is part of the Package.swift but the next one is not, it is specified in one dependency.

**Comment by calebkleveter** [comment]
Yeah, sorry. You'll have to setup SSH fo it to work then. It's actually pretty straight forward: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by vzsg** [comment]
Or you could temporarily use an insteadOf rule in git config to overwrite git URLs into HTTPS URLs. See [here](https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe) for an example.

**Comment by vzsg** [comment]
Another workaround option would be checking out a pre-Cloud version of the toolbox repo (e.g. the 2.0.4 tag), which didn't have the extra deps. Or you could just skip the toolbox altogether 😄.

(None of these two are appropriate if you want to interact with Vapor Cloud though.)

**Comment by segabor** [comment]
@calebkleveter in order to make it work vapor-toolbox project must contain my public key. But this way is supposedly a no go.
@vzsg thanks for the tip. I don't need cloud yet just a working toolbox. Thanks.

**Comment by joscdk** [comment]
@segabor since the package is public, it dosn't need to have your public key, you just need to have an SSH key locally

**Comment by segabor** [comment]
@joscdk you're absolutely right! I was under impression that I already updated my GH profile with the ssh key I'm using now. I did it now swift package update works like a charm.
Sorry for making confusion, closing ticket as non-issue.
Thanks guys!
