### ISSUE TITLE
Build before running [vapor version] error 

### ISSUE THREAD

**Issue by CodeYourDay** [vapor/toolbox#244]
Run the `vapor --version` command before the project build, will print error info :

```
Vapor Toolbox: 3.1.10
Error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “checkouts” doesn’t exist." UserInfo={NSFilePath=./.build/checkouts/, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7f81fec1a6a0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
```

Running `vapor heroku init ` prints the same error: 

```
Setting buildpack...
Are you using a custom Executable name?
y/n> n
Setting procfile...
Error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “checkouts” doesn’t exist." UserInfo={NSFilePath=./.build/checkouts/, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fdf22403b70 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
```

**Comment by sankarsubramanian** [comment]
I am having the same issue.
@CodeYourDay Could you explain how to resolve this one or Which version of heroku buildpack that you set in heroku.
For Info:
I am setting custom build pack as "https://github.com/vapor-community/heroku-buildpack"

**Comment by vzsg** [comment]
That should be correct. See if you have  the `.build` folder checked into git by mistake - and  if it's there, remove it from source control  and add it to  .gitignore.

**Comment by sankarsubramanian** [comment]
@vzsg Thanks for your info. There is no .build folder in repository.
While add the heroku buildpack manually in heroku app page it is working fine.
Only via terminal I am getting the error info and same error while checking vapor version in terminal
vapor --version
Vapor Toolbox: 3.1.10
Error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “checkouts” doesn’t exist." UserInfo={NSFilePath=./.build/checkouts/, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fd6a0501190 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}

**Comment by vzsg** [comment]
Oh, never mind me then. I thought there was a Heroku deployment issue in the background.
