### ISSUE TITLE
Distributed Toolbox builds should not depend on absolute paths

### ISSUE THREAD

**Issue by vzsg** [vapor/toolbox#255]
As previously reported in vapor/vapor#1211, the toolbox binaries that are available on the Homebrew tap contain references to libssl and libcrypto as absolute paths. This completely breaks the toolbox if Homebrew is not installed in the standard location `/usr/local`.

The proper solution would be either leaving out Vapor completely from the toolbox (so the end result will not depend on libssl/libcrypto), or rewriting the dependencies during the release process with `install_name_tool` to find the shared libraries via `@rpath`.

Considering how the old toolbox is not receiving even trivial fixes, it would at least be nice if the 2018 version did not suffer from this issue when it's released.

**Comment by tanner0101** [comment]
toolbox 18.0 already has a fix for this issue on linux. It uses the `-rpath` option during build instead of `install_name_tool`, but achieves the same effect. See https://github.com/vapor/toolbox/blob/18/ubuntu.Dockerfile#L6

The idea is to do the same for macOS 👍
