### ISSUE TITLE
Add support for the Swift REPL

### ISSUE THREAD

**Issue by MrLotU** [vapor/toolbox#256]
This issue bridges https://github.com/vapor/vapor/issues/1585 over to the toolbox repo.

I think it'd be awesome to have a command in the toolbox that does this for you, so instead of having to do all of this yourself, you'd be able to run something along the lines of
`vapor interactive` or `vapor shell` which would start the Swift REPL with your app linked.

Related: https://swift.org/blog/swiftpm-repl-support/ (this might make this not needed anymore)

**Comment by calebkleveter** [comment]
This will be much easier in Swift 5 because `swift run` now has the `--repl` flag.

**Comment by MrLotU** [comment]
Oooh! is there a link where I can read more about that?

**Comment by MrLotU** [comment]
This now works with the `--repl` flag
