### ISSUE TITLE
How to change target name

### ISSUE THREAD

**Issue by mhergon** [vapor/toolbox#264]
Hi,

I have multiple Vapor projects under same Xcode Workspace, but all projects appears with scheme name "Run".
Is there any way to change this name when `vapor xcode` generate the project?
I can change the name on the project, but after every `vapor update` or `vapor xcode` command, the "Run" name appears again.

Thanks!

**Comment by linqingmo** [comment]
In `Package.swift`, there's `.target(name: "Run", dependencies: ["App"]),`. Change "Run" to any name you like before `vapor xcode`.

**Comment by mhergon** [comment]
Yes, it was the first thing I tried, but...
```
Generating Xcode Project [Failed]
'Test' /Users/mhergon/Desktop/Test: error: could not find source files for target(s): Test; use the 'path' property in the Swift 4 manifest to set a custom target path

Error: Could not generate Xcode project: 'Test' /Users/mhergon/Desktop/Test: error: could not find source files for target(s): Test; use the 'path' property in the Swift 4 manifest to set a custom target path
```

**Comment by linqingmo** [comment]
Sorry, I think you also need to change `Sources/Run`, the `Run` folder to your target name.

**Comment by mhergon** [comment]
Oh yeah! Thanks, it's working now
