### ISSUE TITLE
README.txt in release says to move *.dylib files

### ISSUE THREAD

**Issue by BinaryHammer** [vapor/toolbox#265]
If I download a Vapor release 3 or beta 18 there is only a binary and a `README.txt`.

The `README.txt` has the following content:

> Manual Install Instructions for Vapor Toolbox v18.0.0-beta.15
>
> \- Move *.dylib files into /usr/local/lib
> **- Move executable vapor-beta into /usr/local/bin**
> \- Type 'vapor-beta --help' into terminal to verify installation

There are no `.dylib` files in the release.
I think it means: *Find your own dylib of the dependencies, which are not described here and implicitly mean the dependencies `ctls` and `libressl`.*

Also there is no hint to a manual install in the Docs (homebrew can be [insecure](https://applehelpwriter.com/2018/03/21/how-homebrew-invites-users-to-get-pwned/)).

**Comment by joscdk** [comment]
@BinaryHammer just to be sure is it your intention to install the new beta toolbox, which is still very much work in progress?

**Comment by BinaryHammer** [comment]
The beta and 3.2.10 both have the same `README.txt`.

**Comment by grundoon** [comment]
Essentially a duplicate of https://github.com/vapor/toolbox/issues/251

**Comment by BinaryHammer** [comment]
@grundoon yes you are correct.
