### ISSUE TITLE
Name of the release file is too general

### ISSUE THREAD

**Issue by BinaryHammer** [vapor/toolbox#266]
The name of the release file for Vapor is `macOS-sierra.tar.gz` should be more like `vapor-toolbox-3.1.10-macOS-sierra.tar.gz`.
After some time people may not know anymore what the file was about.

**Comment by tanner0101** [comment]
We're going to start using Homebrew bottles for the new toolbox, and those have a fixed naming scheme similar to what you requested here. 👍
