### ISSUE TITLE
Vapor Toolbox won't run if Homebrew is installed to alternate prefix

### ISSUE THREAD

**Issue by SteelPangolin** [vapor/toolbox#268]
### Steps to reproduce

1. Install Homebrew to any prefix other than `/usr/local`. This is a [supported Homebrew configuration](https://docs.brew.sh/Installation) and is useful for development and avoiding conflicts with non-Homebrew apps that insist on using `/usr/local`, although [documented as requiring some care in packaging](https://docs.brew.sh/FAQ#why-do-you-compile-everything).
2. Install Vapor Toolbox using `brew install vapor/tap/vapor`.
3. Run any `vapor` command.

### Expected behavior

`vapor` can be installed [through official Homebrew tap](https://docs.vapor.codes/3.0/install/macos/) and run, regardless of Homebrew prefix.

### Actual behavior

`vapor` executable is linked against `libssl` and `libcrypto` in `/usr/local/opt/openssl/lib` and cannot be run.

```
$ vapor new Foo
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/user/homebrew/bin/vapor
  Reason: image not found
[1]    25050 abort      vapor new Foo

$ otool -L $(which vapor)
/Users/user/homebrew/bin/vapor:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1452.23.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1452.23.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1161.10.0)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 59.1.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

### Environment

* Vapor Framework version: 3.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14 Mojave
* `brew --version`: Homebrew 1.8.6
* `brew --prefix`: `/Users/user/homebrew`

### Workarounds

- Install Homebrew somewhere else.

### Possible fixes?

- Build and bottle `vapor` executable in such a way that it uses relative paths for `libssl` and `libcrypto`.
- Extend Homebrew formula for `vapor` to use Xcode's [`install_name_tool`](https://www.unix.com/man-page/osx/1/install_name_tool/) to rewrite library paths in the `vapor` executable after downloading it, if Homebrew prefix is not `/usr/local`.

**Comment by tanner0101** [comment]
See also https://github.com/vapor/toolbox/issues/255. 

We're hoping to fix this with Toolbox 18 executables. At the very least, the way Toolbox 18 will be uploaded to Homebrew will allow you to more easily build from source.

**Comment by tanner0101** [comment]
OpenSSL is no longer a requirement.
