### ISSUE TITLE
Creating a new Vapor Project with a name that clashes with a dependency project fails poorly

### ISSUE THREAD

**Issue by josereyes** [vapor/toolbox#269]
When creating a new vapor project, if you use a name that clashes with a dependency project, it appears to succeed initially, but then when you try to open the xcode project, you learn it does not yet exist and the error produced is difficult to understand. 

### Steps to reproduce

- Create a new Vapor project named "core" e.g. `vapor new core --template=twostraws/vapor-clean`
- `cd` into the `core` folder and run `vapor xcode`

### Expected behavior

Vapor requires project names to be distinct from dependency projects. As such, this should return an error that is easier to understand e.g. "Your project named `core` project could not be created because `core` is already being used by another vapor dependency project. Please choose a different name."

### Actual behavior

It will respond with:
```
Generating Xcode Project [Done]
Select the `Run` scheme to run.
Open Xcode project?
y/n>
```

- type `y` and enter

It responds with:
```
Opening Xcode project...
Error: backgroundExecute(code: 1, error: "The file <directory>core/*.xcodeproj does not exist.\n", output: "")
```

### Environment

* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.4

**Comment by tanner0101** [comment]
Potentially the toolbox could have a list of incompatible module names either hard-coded or generated somehow w/ SPM. Then we could give better error messages up front.

**Comment by abhisheknaidu-462** [comment]
> I run into the same issue. And I resolve it by selecting the correct version of the command line tools in Xcode. Hope this helps.
> 
> ![image](https://user-images.githubusercontent.com/4176744/55709592-403f0700-5a1b-11e9-989d-45d0e04340aa.png)

Thanks man, this saved my day :)
