### ISSUE TITLE
DownloadError: Failed to download resource "vapor"

### ISSUE THREAD

**Issue by yo2bh** [vapor/toolbox#270]
I am getting the following error when I tried to install the vapor.

tim$ brew install vapor/tap/vapor
==> Installing vapor from vapor/tap
==> Downloading https://github.com/vapor/toolbox/releases/download/3.1.10/macOS-
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws

**curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "vapor"
Download failed: https://github.com/vapor/toolbox/releases/download/3.1.10/macOS-sierra.tar.gz**

Please provide a solution for the same.

**Comment by snowtom** [comment]
I get the same problem!

Error: vapor: Failed to download resource "vapor"
Download failed: https://ghcr.io/v2/homebrew/core/vapor/blobs/sha256:7a6b32eb224796649a9e2024e7a430124bdebaf4253c42ca90a755aa3fe4690b

**Comment by 0xTim** [comment]
@snowtom make sure you don't have the vapor tap installed (we're in Homebrew core now) and it's not a network issue
