### ISSUE TITLE
Vapor 4 - can't use `vapor new` for directories with spaces

### ISSUE THREAD

**Issue by MaherKSantina** [vapor/toolbox#280]
I'm trying vapor-beta command to create an app using vapor 4, so I'm executing:
```
vapor-beta new hello -n
```

However, it looks like the command doesn't work if I'm in a directory where one of the directories has a space in the name, for example, here's my working directory:

```
/Users/Shared/Relocated Items/Security/vapor
```

When I try the command, I get this error:

```
vapor sudo vapor-beta new hello -n
Password:
name: hello
fluent: No
Generating project files...
+ Package.swift
error:
cat: /Users/Shared/Relocated: No such file or directory
cat: Items/Security/vapor/.vapor-template/Package.swift: No such file or directory
```

It looks like it's picking up the directory as 2 separate directories

### Steps to reproduce
`cd` to a directory that has a space in it and run the command

### Expected behavior
Create the project with no errors

### Actual behavior
Getting an error

### Environment

* Vapor Framework version: 4
* Vapor Toolbox version: 3.1.10
* OS version: macOS Catalina 10.15

BTW really excited to try this thing out! Great job on the beta release ❤️

**Comment by MrLotU** [comment]
Thanks for raising @MaherKSantina. I've transferred your issue to the Toolbox repository since this is a toolbox issue 😄

**Comment by MaherKSantina** [comment]
Ohh haha no problem sounds good! 👍

**Comment by mredig** [comment]
I was about to try to contribute a fix for this, but found that it appears to have already been fixed in  `a2beb7f2d5b3cc723be6c3741ea98397ad307731` (not sure how to link to a commit) which is already in `master`.

**Comment by MrLotU** [comment]
Fixed per https://github.com/vapor/toolbox/commit/a2beb7f2d5b3cc723be6c3741ea98397ad307731

Thanks @mredig for noticing 👍

**Comment by 0xTim** [comment]
@MrLotU this probably needs releasing, though we may need @tanner0101 for that
