### ISSUE TITLE
XCodeCommand could be updated to allow direct open of Package.swift in XCode

### ISSUE THREAD

**Issue by tdotclare** [vapor/toolbox#281]
With native SPM support in XCode 11, xcode command might be split to prompt user with option of simply opening Package.swift in XCode rather than generating an XCode project.

Working directly with Swift packages doesn't seem to offer the full range of options that XCode projects do, so keeping a project builder option would probably be useful, but it's nice to have package updating directly in XCode without having to regenerate the project and losing schema and custom settings, and probably satisfies the vast majority of cases.

**Comment by 0xTim** [comment]
I vote just getting rid of the command all together and then people who need an actual project can just do `swift package generate-xcodeproj`

**Comment by tanner0101** [comment]
`vapor xcode` now opens as native SPM project (no xcodeproj generation).
