### ISSUE TITLE
Vapor cloud does not work after upgrading to toolbox 3.1.11

### ISSUE THREAD

**Issue by lloydkeijzer** [vapor/toolbox#284]
When executing a vapor cloud command after upgrading to toolbox 3.1.11 like this:

`vapor cloud <any command (like deploy and me etc...)>`

I get the following error:

```
dyld: lazy symbol binding failed: Symbol not found: _EVP_aes_128_cbc_hmac_sha256
  Referenced from: /usr/local/opt/vapor/lib/libssl.1.0.0.dylib
  Expected in: /usr/local/opt/vapor/lib/libcrypto.1.0.0.dylib

dyld: Symbol not found: _EVP_aes_128_cbc_hmac_sha256
  Referenced from: /usr/local/opt/vapor/lib/libssl.1.0.0.dylib
  Expected in: /usr/local/opt/vapor/lib/libcrypto.1.0.0.dylib
```

## Expected behavior

Use cloud commands with no errors

## Actual behavior

Getting an error

## Environment

    Vapor Framework version: 3
    Vapor Toolbox version: 3.1.11
    OS version: macOS Mojave 10.14.6

**Comment by tanner0101** [comment]
I just pushed `3.1.12` which appears to fix this on my machine at least. LMK if that works for you, thanks :)

**Comment by lloydkeijzer** [comment]
It's working now as of 3.1.12, thank you :)!!
