### ISSUE TITLE
Homebrew installs macOS version on Arch Linux

### ISSUE THREAD

**Issue by segabor** [vapor/toolbox#285]
vapor cloud login command fails with an obscure error message

```
[segabor@csihuhu YetAnotherCounter]$ vapor cloud login
error:
ResponseError(error: true, reason: "User has not been authenticated.")
```
Message indicates user name or password is incorrect. However I can log in on my MacBook and via browser. The same attempt fails on my Arch Linux machine.

Toolbox: 3.1.11 (installed via linux brew)
Swift: 5.1.2 (latest release)
Arch Linux: 5.4.1-arch1-1 (latest)

**Comment by segabor** [comment]
UPDATE: latest vapor toolbox does not work on macOS Catalina too producing the same symptoms described above.

Toolbox: master
Swift: 5.1.2
macOS: 10.15.1

**Comment by tanner0101** [comment]
See https://github.com/vapor/toolbox/issues/284, `3.1.12` will hopefully fix. If not, let me know. Thanks!

**Comment by segabor** [comment]
Dear @tanner0101 did not help. I guess there must be around base64 decoding or something related to username / password handling.
I tried to simulate the login with the following curl command:
```sh
curl -i -X POST \
    -H 'Authorization: Basic <uname:pwd encoded in base64>'
    https://api.v2.vapor.cloud/v2/auth/users/login
```
but I got the same User has not yet been authenticated message. Perhaps I forgot to set some headers.
The only was I was able to login via toolbox is on my macOS installed via homebrew. But the one I compiled from scratch behave the same way as the Linux version.

**Comment by segabor** [comment]
Most probably the issue is on the server side. It turned out that only released vapor toolboxes work (and only on macOS) as they connect to `https://api.vapor.cloud` in contrary to latest code which uses new v2 endpoints. And it never worked according to my experience.
For unknown reason, linuxbrew installs vapor toolbox that also relies on v2. But it can be due to failure of linuxbrew.
**UPDATE** linux package is broken. linuxbrew always want to install macOS version (and it does).
So the only option is to build the latest release, requiring Swift 3.x version which is a bit hard to install on Arch Linux.

**Comment by tanner0101** [comment]
@segabor hmmm. Toolbox 3.x should always use Vapor Cloud 1, only the latest version on `master` branch (Toolbox 18.x) uses Vapor Cloud 2. Is it possible linuxbrew is trying to build from the `master` branch instead of pulling the latest stable tag, `3.1.12`?

**Comment by segabor** [comment]
I changed issue title as it became clear to me that it's linux brew that installs incorrect binary.

**Comment by segabor** [comment]
Going further on this round I found several problems that needs to be addressed to have Linux support:
1. vapor brew formula has no idea about multi-platform support ( ticket opened https://github.com/vapor/homebrew-tap/issues/25 )
2. github releases page contains only macOS binary package - so brew won't be able to download linux binary
3. toolbox project looks outdated - at least I can't compile with Swift 5.

**Comment by tanner0101** [comment]
1: Yes that's true. TBH I had no idea Homebrew was on Linux before you mentioned it. See that ticket for additional comments.
2: Yeah the way this is done currently is I create the binaries by hand and attach them to the release. I'm hoping this is all automated away once we're in Hombrew-core
3: Toolbox 3 is very old (build on Vapor 2). Toolbox 18 (master branch) is what we'll be releasing with Vapor 4.

**Comment by segabor** [comment]
Ok, I'm fine with the master branch. When is it expected to work with v2 API?
