### ISSUE TITLE
vapor-beta won't install

### ISSUE THREAD

**Issue by grosch** [vapor/toolbox#288]
> % brew install vapor/tap/vapor-beta
==> Installing vapor-beta from vapor/tap
==> Downloading https://github.com/vapor/toolbox/archive/18.0.0-beta.19.tar.gz
==> Downloading from https://codeload.github.com/vapor/toolbox/tar.gz/18.0.0-beta.19
######################################################################## 100.0%
==> swift build --disable-sandbox
Last 15 lines from /Users/scott/Library/Logs/Homebrew/vapor-beta/01.swift:
/private/tmp/vapor-beta-20191219-36193-1g41ml/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:9:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "env", short: "e")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191219-36193-1g41ml/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:11:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "branch", short: "b")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191219-36193-1g41ml/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:32:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "app", short: "a")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191219-36193-1g41ml/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:34:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "env", short: "e")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191219-36193-1g41ml/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:36:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "branch", short: "b")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by niklassaers** [comment]
Also reported in https://github.com/vapor/homebrew-tap/issues/26

**Comment by rpstro02** [comment]
Same issue. Running `brew install vapor/tap/vapor-beta` on Mojave 10.14.5, Swift 5.1.3.

**Comment by certainly** [comment]
Same here.

**Comment by rpstro02** [comment]
Same results cloning and running `swift build -c release --disable-sandbox`
