### ISSUE TITLE
Vapor Toolbox 3.1.12 claims to be 3.1.10. Is it?

### ISSUE THREAD

**Issue by marc-medley** [vapor/toolbox#292]
A manual download and examination of Vapor Toolbox 3.1.12 (https://github.com/vapor/toolbox/releases/tag/3.1.12) found the `vapor` binary claimed to be "3.1.10"

``` 
vapor-toolbox-3.1.12> ls -l
total 32032
-rw-r--r--@ 1 user  staff       199 Aug 17  2018 README.txt
drwxr-xr-x@ 4 user  staff       136 Dec 28 12:50 lib
-rwxr-xr-x@ 1 user  staff  16396284 Dec  9 18:54 vapor

vapor-toolbox-3.1.12> ./vapor --version
Vapor Toolbox: 3.1.10
vapor-toolbox-3.1.12> 
```

Is the "3.1.12 release" tag actually a "3.1.12" version? or, a "3.1.10" version?

Secondarly, a brew upgrade from what claims to be an older version "3.1.10" generates as "Warning: vapor/tap/vapor 3.1.12 already installed." can confuse users trying to upgrade to the latest version. 

* <https://stackoverflow.com/questions/59501047/terminal-vapor-update-is-using-swift-tools-version-3-1-0-which-is-no-longer-supp/59512417#59512417>.

**Comment by lowlabs** [comment]
Still seeing this in 3.1.13

**Comment by tanner0101** [comment]
The latest few updates haven't required recompiling the toolbox. They've all been updates to fix Homebrew issues. You can use `brew` to check the version.

**Comment by linuxbiekaisar** [comment]
Expecting help for installing vapor and shows kaisarhamid@Cli:~/toolbox$ swift build -c release --disable-sandbox
/home/kaisarhamid/toolbox: error: package at '/home/kaisarhamid/toolbox' requires a minimum Swift tools version of 5.2.0 (currently 4.2)
![Screenshot from 2020-04-10 02-01-02](https://user-images.githubusercontent.com/60579529/78935754-2b360180-7acf-11ea-9dec-00eadd22ce39.png)

**Comment by 0xTim** [comment]
@linuxbiekaisar what version of Swift do you have installed?

**Comment by linuxbiekaisar** [comment]
inall

**Comment by linuxbiekaisar** [comment]
installed swift 4.2 but downloaded 5.2 failed to installed it

**Comment by 0xTim** [comment]
You'll need Swift 5.2 to build current master. If you installed Swift via apt, remove it (as the APT repo is deprecated) and install from swift.org instead

**Comment by linuxbiekaisar** [comment]
thanks for suggestion
