### ISSUE TITLE
vapor-beta new doesn't correctly add fluent driver

### ISSUE THREAD

**Issue by kylebshr** [vapor/toolbox#297]
Using the latest `vapor-beta`, when I answer yes to Fluent and choose a driver, the `Package.swift` file is missing the db name and version for the driver.

```
.package(url: "https://github.com/vapor/fluent--driver.git", from: "-beta")
```

**Comment by saroar** [comment]
i cant event install vapor beta 
```
// 🍏  vapor-beta new hello -n
Cloning template...
name: hello
Would you like to use Fluent?
y/n> no
fluent: No
Generating project files
+ Package.swift
Error: cat: /Users/alifdev/Security/Developer/Swift/Mikhail: No such file or directory
cat: Arzhaev/BackEnd/.vapor-template/Package.swift: No such file or directory
```

**Comment by 0xTim** [comment]
@saroar that looks like a network issue where it's failed to clone the template and swallowed the error (something that needs fixing!)
Can you clone vapor/template manually?

**Comment by saroar** [comment]
toolbox cant read folder name with white space so I rename my folder it's working

**Comment by 0xTim** [comment]
Looks like that's covered under #280 so should get fixed.

@kylebshr I'm closing this as I believe the original issue is now fixed
