### ISSUE TITLE
Beta build issues

### ISSUE THREAD

**Issue by bhartsb** [vapor/toolbox#299]
Following the instructions at: https://docs.vapor.codes/4.0/install/ubuntu/
OS is ubuntu 18.04

and running the command: swift build -c release --disable-sandbox

I see: 

Updating https://github.com/apple/swift-nio.git
Updating https://github.com/vapor/leaf-kit.git
Fetching git@github.com:vapor/console.git
error: Failed to clone git@github.com:vapor/console.git:
    Cloning into bare repository '/home/user/toolbox/.build/repositories/console-0df01bce'...
    Host key verification failed.
fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.

In Package.swift maybe this line is wrong:
.package(url: "git@github.com:vapor/console.git", .branch("master")),

and should be changed to:
.package(url: "https://github.com:/vapor/console-kit.git", .branch("master")),

That seems to resolve that issue but then there are a few warnings and a bunch of errors which I will attach as a separate file.

I see that there is a folder with release files:
.build/x86_64-unknown-linux/release

Small thing but doc says the folder will be:
.build/release/vapor

In Package.swift I see a target: executable which there is a file Executable.product
(not yet familiar with extensions like .build and .product)

[vaporBuildWarningsAndErrors.txt](https://github.com/vapor/toolbox/files/4037973/vaporBuildWarningsAndErrors.txt)

**Comment by 0xTim** [comment]
The docs definitely need updating. 

As for the build errors - what version of Swift are you running on Linux?

**Comment by bhartsb** [comment]
I'm running Swift version 5.1.3 (swift-5.1.3-RELEASE)
Attaching the contents of my .build/release folder.  What too are the steps remaining? 
There seems to be mis alignment with the docs.

[releaseFolder.txt](https://github.com/vapor/toolbox/files/4041847/releaseFolder.txt)

**Comment by 0xTim** [comment]
Yeah the docs will most likely be wrong since everything's in beta. Do you need the toolbox? `swift build` will do most of what you need without the toolbox

**Comment by bhartsb** [comment]
Hi Tim,
I don’t know if I need it or not since I’m completely new to Vapor.
What I need is a web socket server with native TLS and a redis client.

**Comment by bhartsb** [comment]
@0xTim Is there some instructions for setting up a Vapor 4 project and building it with Swift Build?

**Comment by bhartsb** [comment]
It seems that master branch is the latest beta.  It is confusing because there are online blog resources that are out of date referencing the tool as for example, vapor-beta.   Master branch does build however.

When I set use vapor new <someserverprojectname> --template=web it doesn't seem to use the web template.

So is anything in the old template still viable?  As someone completely new it is hard to get a feel for what is the organization of Vapor-4 without any meaningful docs.  I've code dived a bit but don't have time (even if I would like to) to spend full days or longer trying to figure it out.

https://github.com/vapor/http/blob/master/Sources/HTTPKit/Server/HTTPServer.swift

**Comment by 0xTim** [comment]
@bhartsb if the toolbox isn't working in Linux (I have no idea if it is or not) then you can do `git clone git@github.com:vapor/api-template.git MyVaporApp && cd MyVaporApp && git checkout 4 && rm -rf .git && git init` to emulate what the toolbox does. Then inside there just do `swift run` or `swift build`

**Comment by bhartsb** [comment]
It seems to be working from master.  Initially I thought I was to build from the Vapor-4 branch.

**Comment by 0xTim** [comment]
Glad it's working!
