### ISSUE TITLE
Vapor build error: exec.swift: value of optional must be unwrapped on Ubuntu 18.04

### ISSUE THREAD

**Issue by EricShapiro** [vapor/toolbox#303]
I'm getting the following error building the vapor beta:

/home/eshapiro/vapor-beta/toolbox/Sources/VaporToolbox/exec.swift:36:47: error: value of optional type 'posix_spawn_file_actions_t?' must be unwrapped to a value of type 'posix_spawn_file_actions_t'

Changing posix_spawn_file_actions_t's ? to a ! in exec.swift seems to have fixed the problem.

Versions:
Vapor Toolbox 18.0.0-beta.27
Swift version 5.2-dev (Swift 47106335d2)
Ubuntu 18.04: Linux ubuntu 5.3.0-28-generic 30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tanner0101** [comment]
Fixed in https://github.com/vapor/toolbox/commit/6d8ffe7afc8ad49bdfde696c87db430ebb68a1e1, let me know if that works. (You can just pull `master` instead of a specific version)

**Comment by EricShapiro** [comment]
Yes, that works. Thx.
