### ISSUE TITLE
Vapor toolbox 3.1.12 on Linux requires Swift tools 5.2.0 instead of 5.1.0!! FIX IT NOW!

### ISSUE THREAD

**Issue by Olausfransen** [vapor/toolbox#307]
From Swift.org, the latest version is as of today 5.1.5. Once downloaded on a Ubuntu 18.04.4 LTS I tried to install Toolbox. Since I don't want to work on beta versions, I wanted to download the latest version which is as of today 3.1.12. If I do so, I got an error for console-kit which requires Swift tool 5.2.0 whereas only 5.1.0 is installed (since 5.1.5 is the latest released version).
Could you please fix the repo so that the latest Toolbox (3.1.12) only requires the latest release of Swift tools (5.1.0)?
Thank you!
/Ola

**Comment by Ashitaio** [comment]
Same issue for me: I have Catalina 10.15.3 and VirtualBox with Ubuntu 18.04.4 LTS but cannot install Vapor due to Console-kit that requires Swift tools 5.2.0.
Would be nice to fix this issue! Thanks

**Comment by 0xTim** [comment]
Can you check this is fixed in 3.1.13?

**Comment by tanner0101** [comment]
3.1.12 was accidentally tagged against the wrong branch. 3.1.13 should work now, sorry about that.

**Comment by Olausfransen** [comment]
Thanks! I confirm this is now working perfectly with branch 3.1.13 on Ubuntu 18.04.4 LTS. Just got some warnings in Yams (dangling pointer ...) in Emitter.swift but otherwise all fine.
Really appreciate the quick fix: you rock!
