### ISSUE TITLE
Custom template issues

### ISSUE THREAD

**Issue by fananek** [vapor/toolbox#308]
**Issue:**
1.) Only first occurrence of mustache section within a file is being rendered.
2.) Files from Resources/Views folder are being copied even if `leaf` variable equals false.

**Details:**
I was trying to implement Leaf support into Vapor template. 
See: [https://github.com/fananek/template-leaf](https://github.com/fananek/template-leaf) for reference. It already contains updated files how I suppose they shall be.

- manifest.yml - new `leaf` variable(bool) + updated files section (if `leaf` then copy leaf templates)
- Dockerfile - conditionaly include command to copy Resources folder from build to app image
- Package.swift - add leaf as a dependency and target.app dependency
- Resources/Views - new sample files (base.leaf and hello.leaf)
- configure.swift - add leaf import + leaf config
- routes.swift - add leaf import + sample route using leaf templates

**Comment by 0xTim** [comment]
This should be closed in #351
