### ISSUE TITLE
Encountering "illegal hardware instruction" during "vapor build"

### ISSUE THREAD

**Issue by stevapple** [vapor/toolbox#310]
**Output:**

```shell
$ vapor build
Building project...
[1]    14783 illegal hardware instruction (core dumped)  vapor build
```

Vapor Toolbox version 18.0.0-beta.28 built and used on Ubuntu 18.04 using Swift 5.2 (the official prebuilt package). I've tested my project with Swift 5.2 (Xcode 11.4) on macOS before uploading it to my Ubuntu server. No permission issues.

**Comment by stevapple** [comment]
Also, building the `master` branch reports an `error: missing LinuxMain.swift file in the Tests directory`.

**Comment by 0xTim** [comment]
@stevapple for building master you need `swift build --enable-test-discovery`

For the illegal instruction, what's the output of `swift build`?

**Comment by stevapple** [comment]
> For the illegal instruction, what's the output of `swift build`?

```
error: cyclic dependency declaration found: my-site -> my-site
```

`my-site` is the name of my Vapor project, using Vapor 4 and Leaf 4.

**Comment by 0xTim** [comment]
Here's something that might help - https://forums.swift.org/t/circular-dependencies-in-swiftpm/13580/8

Closing as this isn't an issue with the toolbox

**Comment by 0xTim** [comment]
(But feel free to post more questions/ask on Vapor Discord!)

**Comment by stevapple** [comment]
It may still be a toolbox-related issue as the project is almost the pure template created by `vapor new`. 

Also I’ve tested with the original template w & w/o Fluent...Getting the same output. 

Maybe an issue in `vapor/template`?

**Comment by 0xTim** [comment]
What does your Package.swift look like? Because it works for me

**Comment by stevapple** [comment]
Works on Ubuntu with Swift 5.2?

I simply used `vapor new my-site -n && cd my-site && vapor build`. 

It works well on macOS but fails on Ubuntu.

**Comment by 0xTim** [comment]
Yes Ubuntu 18.04 with 5.2 release. You said it's "almost the pure template" - what do you mean by that and what does your Package.swift look like?

**Comment by stevapple** [comment]
Well, when I posted this issue I was using my own project, which has some minor differences with the template. For `Package.swift`, there’s one more dependency:

```swift
.dependency(url: "https://github.com/vapor/leaf.git", from: "4.0.0-rc")
```

However, I tested the raw templates later on my machine, and still got the ‘cyclic dependency’ error. I’ve done nothing to the template at all 😂 Besides, the toolchain tarball is gpg-verified so I’m sure it’s not broken.

**Comment by 0xTim** [comment]
I'd advise you post in the Vapor Discord then as this is better suited to there

**Comment by stevapple** [comment]
I’ve got the point. `swift build` works when `--enable-test-discovery` flag is specified, while the toolbox doesn’t. 

Maybe we should change `try exec(Process.shell.which("swift"), ["build"] + context.input.arguments)` into `try exec(Process.shell.which("swift"), ["build", "--enable-test-discovery"] + context.input.arguments)` in `Build.swift`?

**Comment by 0xTim** [comment]
That sounds like a good idea

**Comment by stevapple** [comment]
I've made it a PR, which you can check it out. 

Also, the `cyclic dependency` error is, in fact, another one, triggered by a SwiftPM bug which is tracked as `SR-11826`.
