### ISSUE TITLE
Vapor Ubunutu 14.04

### ISSUE THREAD

**Issue by chrigu1981** [vapor/toolbox#315]
just installed vapor with the official installation guide. installation was successful on ubuntu 14.04

### Actual behavior

`vapor --version`

produces:

```
vapor: symbol lookup error: vapor: undefined symbol: _T0s27_ContiguousArrayStorageBaseC16countAndCapacitys01_B4BodyVvpWvd
```

### Environment

swift-version: `Swift version 4.2 (swift-4.2-RELEASE)
Target: x86_64-unknown-linux-gnu`

**Comment by tanner0101** [comment]
This is due to Swift ABI breakage. Vapor's APT repos are deprecated. The best way to install vapor/toolbox on Linux is via Linux brew or compiling the desired toolbox version (`master` is latest). More info here: https://docs.vapor.codes/4.0/install/ubuntu/
