### ISSUE TITLE
Compile error on (previously) unsupported OSes

### ISSUE THREAD

**Issue by arodeus** [vapor/toolbox#316]
toolbox/Sources/VaporToolbox/exec.swift:42:42: error: value of optional type 'UnsafeMutablePointer<Int8>?' must be unwrapped to a value of type 'UnsafeMutablePointer<Int8>'
    let spawned = posix_spawnp(&pid, argv[0], &fileActions, nil, argv + [nil], envp + [nil])

My Fix follwing:

guard let _argv0 = argv[0] eg:lse {
   fatalError("can't unwrap argv[0]")
}

let spawned = posix_spawnp(&pid, _argv0, &fileActions, nil, argv + [nil], envp + [nil])

**Comment by 0xTim** [comment]
@arodeus what version of `Swift` are you trying to compile with?

**Comment by hgzapata** [comment]
I'm using Swift 5.2.1 on Ubuntu with the same error as above

**Comment by 0xTim** [comment]
Are you 100% sure you're using the 5.2.1 toolchain? `swift --version` is showing 5.2.1? Because I'm unable to reproduce that locally and it's building on CI

**Comment by hgzapata** [comment]
Yes, this is the output in my computer
hernan@omen:~$ swift --version
Swift version 5.2.1 (swift-5.2.1-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by arodeus** [comment]
Hello, sorry for late reply, here's my Swift version.

Swift version 5.2.1 (swift-5.2.1-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by theipple** [comment]
Hello, I am also encountering this issue, I have the same swift version (swift-5.2.1-RELEASE) and I am on Debian (10).
The fix proposed by @arodeus is working for me.

I tried on a fresh install of Ubuntu 18.04.4 and the code compile without any issue.
Then I tried to find what was causing this issue and I think I found it.

On Debian in the `/usr/include/spawn.h` contains:
```
extern int posix_spawnp (pid_t *__pid, const char *__file,
                     const posix_spawn_file_actions_t *__file_actions,
                     const posix_spawnattr_t *__attrp,
                     char *const __argv[], char *const __envp[])
__nonnull ((2, 5));
```

But on Ubuntu there is not the line `__nonnull ((2, 5));`, and so the generated swift interface contains optionals on Ubuntu, but not on Debian.

I hope that my research helps you.

**Comment by arodeus** [comment]
On Ubuntu 19.10 there is the same code in Debian 10, that's the trick.

**Comment by 0xTim** [comment]
Ahhh that makes more sense. Unfortunately both Debian and Ubuntu 19 aren't officially supported Swift platforms, but I'll leave this open in case there's an easy fix (that is backwards compatible)

**Comment by tanner0101** [comment]
If Ubuntu and Debian have different `#if os(...)` definitions then we can work around this easily in https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/exec.swift. If not, we might need to drop into C to access OS specific defines.
