### ISSUE TITLE
how can I fix this

### ISSUE THREAD

**Issue by DLsunset** [vapor/toolbox#319]
I want  to install  Vapor Toolbox on ubuntu 16.04。
and this is what I did 

git clone https://github.com/vapor/toolbox.git
cd toolbox
git checkout master
swift build -c release --disable-sandbox

but there is an error when I run "swift build -c release --disable-sandbox"
"missing LinuxMain.swift file in the Tests directory"

Did i do something wrong？

**Comment by tanner0101** [comment]
Adding the `--enable-test-discovery` flag will fix this: https://stackoverflow.com/questions/61344881/missing-linuxmain-swift-file
