### ISSUE TITLE
vapor build error

### ISSUE THREAD

**Issue by Farini** [vapor/toolbox#320]
Hi, 
I've been trying to get this project to build. It builds on my Mac, but in my server I get the message below after using `vapor clean` and `sudo swift package update` and `swift package tools-version --set-current`

I have reversed the one commit when I added Leaf to the Package.swift and it wouldn't build. So even after I reversed that commit, it is still giving me this same message when I build it from my server (Ubuntu 18 - DigitalOcean.com) which I realize that was huge mistake because now I CANNOT do `vapor run` because vapor just cleaned the working .build folder.

Is there anyway I can:

1. debug exactly what is going on here. Every time I do` vapor build` it stops after: 

> Compile Swift Module 'Core' (25 sources)
> <unknown>:0: error: unable to execute command: Killed
> <unknown>:0: error: compile command failed due to signal 9 (use -v to see invocation)
how do I run the suggestion above?

2. cleanup the entire folder - delete every file and subfolder and do a whole new git checkout to solve this problem. I am not sure if I know how to completely reset the folder containing my project, and restart the "git" in that same folder (proxied in Nginx). - which I would like to avoid because my app depends on that folder.

Anyways any help is greatly appreciated. In the mean time no one can play my game because the server is down. Please help :)

> root@Farini:/TTSS1# sudo vapor build --release
> Building Project [Failed]
> 
> Command:
> build --configuration release
> 
> Error (1):
> error: terminated(1): /usr/bin/swift-build-tool -f /TTSS1/.build/release.yaml main output:
> Output:
> Compile CSQLite sqlite3.c
> Compile Swift Module 'NIOPriorityQueue' (2 sources)
> Compile Swift Module 'Debugging' (3 sources)
> Compile Swift Module 'COperatingSystem' (1 sources)
> Compile CNIOZlib empty.c
> Compile CNIOSHA1 c_nio_sha1.c
> Compile CNIOOpenSSL shims.c
> Compile CNIOOpenSSL helpers.c
> Compile CNIOLinux shim.c
> Compile CNIOLinux ifaddrs-android.c
> Compile CNIOHTTPParser c_nio_http_parser.c
> Compile CNIODarwin shim.c
> Compile CNIOAtomics src/c-atomics.c
> Compile CCryptoOpenSSL shim.c
> Compile Swift Module 'NIOConcurrencyHelpers' (2 sources)
> Compile CBcrypt blf.c
> Compile Swift Module 'NIO' (55 sources)
> Compile CBcrypt bcrypt.c
> Compile Swift Module 'NIOTLS' (3 sources)
> Compile Swift Module 'NIOHTTP1' (9 sources)
> Compile Swift Module 'NIOOpenSSL' (17 sources)
> Compile Swift Module 'NIOWebSocket' (9 sources)
> Compile Swift Module 'NIOFoundationCompat' (1 sources)
> Compile Swift Module 'Bits' (12 sources)
> Compile Swift Module 'Async' (15 sources)
> Compile Swift Module 'Random' (4 sources)
> Compile Swift Module 'Core' (25 sources)
> <unknown>:0: error: unable to execute command: Killed
> <unknown>:0: error: compile command failed due to signal 9 (use -v to see invocation)
> 
> 
> Toolchain:
> /usr/bin/swift
> 
> Help:
> Join our Slack where hundreds of contributors
> are waiting to help: http://vapor.team
> 
> Error: Build failed.

**Comment by 0xTim** [comment]
@Farini try running `swift build` instead. And also don't do `sudo vapor ...`, it shouldn't need super user privileges to run. I suspect you're running out of memory, do you have swap enabled on your box?

**Comment by Farini** [comment]
@0xTim Thank you so much! Yes the problem was memory. Specially because I had just added Leaf I think it went over. Strange that it doesn't give you a warning though.

**Comment by 0xTim** [comment]
Yeah, is a bit weird. Might be worth raising on bugs.swift.org. Glad it's working!
