### ISSUE TITLE
"vapor run" does not react to any parameters

### ISSUE THREAD

**Issue by CoffeBee** [vapor/toolbox#322]
I'm trying to set port, but nothing changes.
<img width="1440" alt="Screenshot 2020-05-26 at 18 36 06" src="https://user-images.githubusercontent.com/40368492/82920324-d3206500-9f7f-11ea-975b-cb2350170d2a.png">

Vapor 18.0.0-beta.28
Swift 5.2.2
Ubuntu 18.04

**Comment by 0xTim** [comment]
Try `swift run Run server --port 8000` instead?

**Comment by tanner0101** [comment]
That should be `--port 8000`. Though I'm surprised there's no error message.

**Comment by tanner0101** [comment]
Fixed in https://github.com/vapor/console-kit/pull/144
