### ISSUE TITLE
Vapor failed to build - missing LinuxMain.swift

### ISSUE THREAD

**Issue by shaqaruden** [vapor/toolbox#326]
I am trying to create a Vapor Docker container but am running into an issue on the build step of installation.

Here is my Dockerfile
```
FROM swift:latest

RUN git clone https://github.com/vapor/toolbox.git vapor

WORKDIR vapor

RUN swift build -c release --disable-sandbox
RUN mv .build/release/vapor /usr/local/bin
```

Here is the output
```
Fetching https://github.com/tanner0101/mustache.git
Fetching https://github.com/apple/swift-log.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/vapor/console-kit.git
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 2.0.0
Cloning https://github.com/tanner0101/mustache.git
Resolving https://github.com/tanner0101/mustache.git at 0.1.0
Cloning https://github.com/apple/swift-nio.git
Resolving https://github.com/apple/swift-nio.git at 2.18.0
Cloning https://github.com/apple/swift-log.git
Resolving https://github.com/apple/swift-log.git at 1.2.0
Cloning https://github.com/vapor/console-kit.git
Resolving https://github.com/vapor/console-kit.git at 4.1.1
error: missing LinuxMain.swift file in the Tests directory
```

I have also tested this on a fresh Ubuntu 20.04 VM with the same result

**Comment by 0xTim** [comment]
You need to pass the `--enable-test-discovery` flag to the build command. Thought that was in the docs but it's not! I'll get that fixed

**Comment by shaqaruden** [comment]
All is good! Thanks!

**Comment by idcrook** [comment]
Was going to file an issue on vapor/console-kit but then searched this GitHub repo for LinuxMain. The docs have it right (I had been using an older, outdated blog post from the web). 
The `--enable-test-discovery` is needed on Ubuntu 20.04 aarch64 swift 5.2.4 (on Raspberry Pi 4) to build toolbox
