### ISSUE TITLE
The --version option does not reference toolbox git tag/branch when building from source.

### ISSUE THREAD

**Issue by fouadhatem** [vapor/toolbox#338]
### Current behavior

Building the toolbox from source doesn't have a version. The way macOS discovers the current toolbox version when using the `vapor --version` option is by asking Homebrew. However, if you build the toolbox from source (as you would typically on Linux), it doesn't have any idea which git tag or branch you used. It therefore reports that the toolbox is not detected or installed.

Also, detecting the version of the vapor framework on non-Homebrew environments would only be possible when executed within a vapor project directory and would only detect the framework version of that specific project. Running `vapor --version` outside of a project folder yields a not-detected-or-installed result, since there is no standard vapor package on Linux or anywhere other than Homebrew.

### Desired behavior

The `vapor --version` option detects the version of the currently installed toolbox on any platform AND the currently installed version of the vapor framework, even if no vapor projects currently exist.

### Possible solution

Ideally, the toolbox itself might be expanded to clone core vapor packages (git repos) into its own local directory. When `vapor new` or `vapor build` is executed at the Cl, the toolbox can clone the necessary packages from its own local catalog, unless newer versions exist on GitHub, or if specific versions of the repos are requested in the project's manifest. Here's how it would work in a nutshell:

1. When executed, the toolbox compares its current tags against the ones currently on GitHub, after first checking for an internet connection and skipping this step if no connection exists.

1. If newer tags exist for one or more of the local repos, it updates its own repos first and then uses those to create and build the new project. (The local vapor repos can also be updated manually by perhaps executing a `vapor update packages` command).

1. If the tags are up to date, then it simply proceeds to building the project from its own repos and fetching any other custom dependencies included in the manifest.

1. If the vapor --version command is executed from within a project folder, it would list the project's vapor framework version in addition to the "system" installed version, by displaying something like: `Framework version for project <Project Name>: <version>`.

1. If something like `vapor --version-all` is executed, it would not just list the vapor framework version; it would also include the versions of all local vapor packages (Fluent, SwiftNIO, etc.).

### Benefits of this approach

1. Reduces build times by mostly skipping out on cloning git repositories (greatly benefits devs working on low bandwidth/metered connections or working offline when starting new projects). 

1. Unifies package management across all current and future platforms (and even negates the need for maintaining a dedicated Homebrew package or any other package repository other than Github obviously).

### Optional features

1. Display current Swift toolchain version and (possibly) be able to upgrade Swift from within the vapor toolbox?

**Note:** The vapor --help page would have to be updated to display all these new options, if implemented.

**Comment by fouadhatem** [comment]
@tanner0101 I started off by simply creating the issue for the `--version` option for the toolchain, but ended up with the above. Couldn't help myself.

**Comment by tanner0101** [comment]
@fouadhatem thanks for the report.

+1 to fixing `--version`. I think the easiest way to do this would be adding a `make install` command that is responsible for setting the version information. It could do this by checking if the current directory is a git repository and has a tag.

As for the local dependencies thing, I believe that is outside the realm of what Toolbox does. That idea should be pitched to SPM itself.
