### ISSUE TITLE
homebrew vapor toolbox install indicates "framework: not found"

### ISSUE THREAD

**Issue by marc-medley** [vapor/toolbox#345]
I just did a clean install of the `vapor` toolbox 18.2.2 via homebrew per the [Vapor Install Toolbox docs](https://docs.vapor.codes/4.0/install/macos/#install-toolbox).

``` sh
brew install vapor

vapor --version
# note: no Package.resolved file was found.
# framework: not found
# toolbox: 18.2.2
```

Note the `vapor --version` output shown above.

The  _"note: no Package.resolved file was found"_ or _"framework: not found"_ leaves one to wonder if the `vapor` toolbox installed OK.

It would be helpful if the `vapor --version` output provided a more clear explanation. In particular, the _vapor project's toolbox status_ and _user's project status_ are conflated in the output. 

``` sh
vapor --version
# vapor toolbox: 18.2.2
# vapor framework for this project: not found in this current working directory (try running `vapor build`) 
# note: no Package.resolved file was found. Possibly not currently in a vapor build directly.
```

**Comment by mohok** [comment]
This still not working on Apple silicon.

**Comment by 0xTim** [comment]
@mohok what do you mean by not working?

**Comment by mohok** [comment]
@0xTim Sorry. I thought that installing with brew have same errors. But, It's okay after `brew link --overwrite vapor`. :)
