### ISSUE TITLE
Template option not recognized (--template, -T)

### ISSUE THREAD

**Issue by eugeniobaglieri** [vapor/toolbox#346]
Good morning, seems that vapor toolbox ignores the --template option.
If i try to launch this command:

```vapor new hello_world --template=web```

I get this:

```Cloning template...
name: hello_world
Would you like to use Fluent? (--fluent)
y/n> y
fluent: Yes
db: Postgres (Recommended)
Generating project files
+ Package.swift
+ main.swift
+ configure.swift
+ routes.swift
+ Todo.swift
+ CreateTodo.swift
+ .gitkeep
+ TodoController.swift
+ AppTests.swift
+ Dockerfile
+ docker-compose.yml
+ .gitignore
+ .dockerignore
Error: Too many arguments: --template=web
```
That termintates, as you can see with an error. 
What it's wrong with this command?

**Comment by 0xTim** [comment]
@eugeniobaglieri the web template is no longer a thing. When Leaf is released then we'll add another option to the toolbox to see if you want to use Leaf and add the necessary files etc

**Comment by eugeniobaglieri** [comment]
it doesesn't work neither using --template='api'

**Comment by 0xTim** [comment]
Correct the API template is deprecated now (and Vapor 4 support was never merged). The base template from `vapor/template` provides everything the API template did
