### ISSUE TITLE
vapor build, Compiling Vapor Application+HTTP+Client.swift Fatal error with Illegal instruction

### ISSUE THREAD

**Issue by kingiol** [vapor/toolbox#348]
> vapor build

> Building project...
[48/79] Compiling Vapor Application+HTTP+Client.swift
Fatal error: result 1: file VaporToolbox/exec.swift, line 55
Illegal instruction

========================

My Linux is `Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-47-generic x86_64)`

Vapor env:
> vapor --version
> framework: 4.32.0
toolbox: 18.2.2

swift version: 
> Swift version 5.3 (swift-5.3-RELEASE)
Target: x86_64-unknown-linux-gnu

My Project is create by `vapor new xxx`, default settings, then `vapor build`, errors happens.

**Comment by siemensikkema** [comment]
@kingiol I tried adding test cases that include your scenario here #349 but the tests pass successfully.

**Comment by siemensikkema** [comment]
@kingiol I believe this is fixed for you if I read https://github.com/vapor/vapor/issues/2512#event-3917410076 correctly. Closing for now.

**Comment by kingiol** [comment]
@siemensikkema Thanks a lot.
