### ISSUE TITLE
Support MacPorts or pkg based distribution method

### ISSUE THREAD

**Issue by ygini** [vapor/toolbox#354]
**Is your feature request related to a problem? Please describe.**
Homebrew is a currently used as the only available distribution method for the Vapor Toolbox. This package manager solution has been known for year to have regular issue with macOS integration, multi user devices, permission management, etc.

Globally this software has a whole history of unstable state and is absolutely not trusted by IT teams in charge of fleet management.

Currently, the [install documentation for macOS](https://docs.vapor.codes/4.0/install/macos/) say `this CLI tool is not required to use Vapor but it includes helpful utilities like a new project creator` but all documentation example are shown with the CLI.

No other method of use are shown in the documentation.

**Describe the solution you'd like**
Vapor toolbox should be distributed in a more reliable method such as signed and notarized package published using the Github release page.

This improve the situation for managed fleet to guarantee to be up to date with the help of solutions like `autopkg` and `munki` or any MDM on the market.

Being compatible with those solution ensure that vapor toolchain can be easily and automatically deployed on a managed fleet without human interaction. Reducing the time needed for a developer to configure a new workstation.

**Describe alternatives you've considered**
The alternative could be to support MacPorts in addition of Homebrew.

MacPorts is a more stable porting system, originally created by Apple as an Open Source project (via the Mac OS Forge initiative). This software is correctly integrated with macOS, has no history of massive system failure and offer proper fleet management capabilities.

**Comment by 0xTim** [comment]
Hi @ygini 
MacPorts is not something we're considering supporting at the moment. The toolbox contains a Makefile and can be installed from source using the Makefile using the [same instructions as Linux](https://docs.vapor.codes/4.0/install/linux/#install-toolbox) if you want to install it manually.
Releasing binaries alongside releases in GH is an interesting idea but as they'd need to be signed we'd need a macOS developer cert for the Vapor org, which is a long term thing. I'll close this issue for now but feel free to ask any other questions!
