### ISSUE TITLE
missing LinuxMain.swift file in the Tests directory

### ISSUE THREAD

**Issue by andrzejlapinski** [vapor/toolbox#359]
### Describe the bug

In Ubuntu 20.04 LTS, command
`swift build -c release --disable-sandbox`
Returns 
`error: missing LinuxMain.swift file in the Tests directory`

### Environment
* OS version: Ubuntu 20.04 LTS

**Comment by 0xTim** [comment]
@andrzejlapinski which documentation are you using to build? It should be `swift build -c release --disable-sandbox --enable-test-discovery`

**Comment by 0xTim** [comment]
Closing this as test discovery is now on by default
