### ISSUE TITLE
Valid form for `--template, -T`?

### ISSUE THREAD

**Issue by marc-medley** [vapor/toolbox#361]
_Is there a valid form for the `--template, -T` option? Or, has this option been removed for current and known future toolbox releases?_

[Issue #346](https://github.com/vapor/toolbox/issues/346) comments indicate that API `--template='api'` and Web `--template='web'` templates are not supported in Vapor 4. However what about a git repository url per the vapor toolbox built-in help?

**Vapor Toolbox Help**

According to the current (homebrew released) Vapor command line help, `--template` would be expected to still be functional with an express git repository url.

``` sh
vapor --version
# toolbox 18.3.3

vapor new --help
# <name> [--template,-T] [--branch] [--output,-o] [--no-commit] 
# 
# Generates a new app.
# 
# Arguments:
#        name Name of project and folder.
# 
# Options:
#    template The URL of a Git repository to use as a template.
```

**Case Template=Repository**

The "URL of a Git repository to use as a template"

```
vapor new vapor_template_apiweb --template=https://github.com/VaporExamplesLab/VaporApiWebTemplate

# Cloning template...
# name: vapor_template_apiweb
# Would you like to...
# ... blah, blah ...
Error: Too many arguments: --template=https://github.com/VaporExamplesLab/VaporApiWebTemplate
```

Error: Too many arguments for all the following forms

* VaporExamplesLab/VaporApiWebTemplate
* https://github.com/VaporExamplesLab/VaporApiWebTemplate
* https://github.com/VaporExamplesLab/VaporApiWebTemplate.git

**Questions Restated**

If the `--template, -T` option remains, what it the correct syntax? If yes, this would be good to add to the command line help.

If the `--template, -T` option remains for url specifications, then perhaps the "Would you like to..." questions do not apply and should be skipped ??

If the `--template, -T` option has removed, then perhaps the command line help should be updated to remove the mention of this template option???

**Comment by 0xTim** [comment]
@marc-medley `vapor new vapor_template_apiweb --template https://github.com/VaporExamplesLab/VaporApiWebTemplate` should work

**Comment by 0xTim** [comment]
Closing this - let me know if it's still an issue!
