### ISSUE TITLE
Make command fails if sudo is not found

### ISSUE THREAD

**Issue by clsource** [vapor/toolbox#362]
### Describe the bug

Using [swift:5.4-bionic](https://github.com/apple/swift-docker/blob/00795177226dc22c1f31a58ec59eefb103e0a9c9/5.4/ubuntu/18.04/Dockerfile) Dockerfile the makefiles fails because Ubuntu 18.04 does not includes _sudo_ by default.

### To Reproduce

- Use `cd toolbox && make install` inside a container created using the `swift:5.4-bionic` image

### Expected behavior

`vapor` command line is installed

### Environment

* Vapor Framework version: 4
* Vapor Toolbox version: 18.3.3
* OS version: Ubuntu 18.04 inside Docker

### Additional context

To solve this I deleted using the sudo command inside the Makefile

```makefile
DEST := /usr/local/bin/vapor

build:
	swiftc ./scripts/build.swift
	./build
	rm ./build
install: build
	mv .build/release/vapor ${DEST}
	chmod 755 ${DEST}
uninstall:
	rm ${DEST}
clean:
	rm -rf .build
```

Another alternative is ensuring the sudo command inside the Dockerfile of swift

```docker
FROM swift:5.4-bionic

RUN apt update
RUN apt install sudo

WORKDIR /src
```

**Comment by 0xTim** [comment]
Simply put, the toolbox is not designed to be run in a Docker container and we can't amount for every different environment. 

If you really need the toolbox inside a container you should manually install it. However there are _very_ few situations where it should be used, you should use `swift build` or `swift run` etc instead

**Comment by Jeffrey-de-Bruijn** [comment]
This is till a problem. I am on RHEL 8 and am forced to run a container to run swift, the official swift container images have no sudo in them.

**Comment by 0xTim** [comment]
@Jeffrey-de-Bruijn what are you trying to use the toolbox for?
