### ISSUE TITLE
New.swift not welcoming to linux developers.

### ISSUE THREAD

**Issue by Jeffrey-de-Bruijn** [vapor/toolbox#389]
line 99 of New.swift says "Then use " + "open Package.swift".consoleText(.info) + " to open the project in Xcode".

Xcode is Apple ecosystem, Vapor supports other platforms too. The message is not welcoming of developers from other platforms. 

Consider changing the message to `Then edit " + "Package.swift".consoleText(.info) + " to start working on your new project` or something along those lines

**Comment by 0xTim** [comment]
Yep agree, we should make this editor agnostic

**Comment by ahmdyasser** [comment]
What if I used this message? 
`"Then use " + "open Package.swift".consoleText(.info) + " to start launch your project`

**Comment by 0xTim** [comment]
Again that's specific to Xcode. It probably need s to be generic like
> Then open your project in your editor - e.g. `open Package.swift` for Xcode of `code .` for VSCode

**Comment by ahmdyasser** [comment]
Will copy and paste that :D 

> Then open your project in your editor - e.g. open Package.swift for Xcode or code . for VSCode
