### ISSUE TITLE
Digital ocean issue: Doesn't start app

### ISSUE THREAD

**Issue by Zuzic** [vapor/toolbox#415]
Hello, I try to build HelloWorld project using Digital ocean (machine: 1vcpu-512mb-10gb, ubuntu22.04)
I am going thought all point in documentation: https://docs.vapor.codes/deploy/digital-ocean/

- Swift version 5.8.1 (swift-5.8.1-RELEASE) 

link: https://download.swift.org/swift-5.8.1-release/ubuntu2204/swift-5.8.1-RELEASE/swift-5.8.1-RELEASE-ubuntu22.04.tar.gz

- toolbox: 18.7.1
link: https://github.com/vapor/toolbox/tree/18.7.1

- vapor:  version framework: 4.77.0

When I call "swift run App serve --hostname 0.0.0.0 --port 8080" I get an error:  emit-module command failed due to signal 9 (use -v to see invocation)

When I try to call "swift build" I get the same error: emit-module command failed due to signal 9 (use -v to see invocation)

Can you please help me, what is wrong?
Regards Yury.

**Comment by 0xTim** [comment]
@Zuzic that's an out of memory issue on the compiler. There _should_ be a fix coming in 5.9 for that but if you enable swap on your machine or up the amount of RAM that should solve the issue
