### ISSUE TITLE
Building from source hangs indefinitely

### ISSUE THREAD

**Issue by brandonmaul** [vapor/toolbox#449]
### Describe the bug

Attempting to build from source (via make install) hanged indefinitely. After compiling the build file `swiftc ./scripts/build.swift` it would run `./build` and never exit.
### To Reproduce

I was using a dev container, so this is pretty easy to reproduce.
Created a new dev container with Swift 5.9 selected from:
https://github.com/swift-server/swift-devcontainer-template

I believe I had to install `make` using apt, since the dev container didn't have it by default.

Attempted to install vapor toolbox as listed out by the docs:
```
git clone https://github.com/vapor/toolbox.git
cd toolbox
git checkout 18.7.4
make install
```

### Expected behavior

The toolbox would build and install appropriately

### Environment

Swift 5.9.2-RELEASE

* Vapor Framework version: N/A
* Vapor Toolbox version: 18.7.4
* OS version: Derivative of Ubuntu:
   Distributor ID: Ubuntu
   Description:    Ubuntu 22.04.3 LTS
   Release:        22.04
   Codename:       jammy

**Comment by gwynne** [comment]
There is a known issue caused by the linker running out of memory which is the most common cause of this kind of problem; does your dev container have at least 2GiB of RAM allocated?

**Comment by brandonmaul** [comment]
@gwynne The dev container had 4GB of RAM allocated at the time. 

I fabricated a fix by modifying the /scripts/build.swift file. and opened it in PR #450
