### ISSUE TITLE
File never compiling on setup

### ISSUE THREAD

**Issue by Harry-KNIGHT** [vapor/toolbox#470]
### Describe the issue

I cannot finish my server setup

### Vapor version

18.7.5

### Operating system and version

macOS Sequoia 

### Swift version

6

### Steps to reproduce

cd toolbox
git checkout 18.7.5
swift build -c release --disable-sandbox --enable-test-discovery

### Outcome

<img width="1319" alt="image" src="https://github.com/user-attachments/assets/77ff2980-2189-4adf-950a-9faf15240906">
stops there, never go over.

### Additional notes

using M1 Air.

**Comment by 0xTim** [comment]
It looks like you're running in a Docker container? Is that correct, if so, which container

**Comment by vzsg** [comment]
To me, the terminal's title suggests a (too) small DigitalOcean droplet connected over SSH, not a Docker container. Not to mention the path `/home/vapor`. This is not a macOS issue and the description should be updated with the real environment.

**Comment by Harry-KNIGHT** [comment]
I'm just following the documentation [there](https://docs.vapor.codes/fr/deploy/digital-ocean/). I do not have deployed my server yet.

Blocked at this command: `swift build -c release --disable-sandbox --enable-test-discovery`

**Comment by Harry-KNIGHT** [comment]
IDK why it worked now. Thanks all :)
