### ISSUE TITLE
Command for Tests/LinuxMain.swift

### ISSUE THREAD

**Issue by LoganWright** [vapor/toolbox#55]
Shouldn't be too hard to build, and it's driving me nuts to maintain this. I would like this to open a new command set `fix` (name pending). I'd like something that conveys the fragility inherent in the command set, but in the meantime, fix is concise and understandable.

The first LinuxMain will be:

```
vapor fix linux-main // fixes linux main
```

If there's time, I _may_ attempt a secondary command

```
vapor fix alltests // fixes the `allTests` variable in tests
```

If secondary implemented

```
vapor fix tests // does alltests _and_ linuxmain
```

The fix commandset can be used for other annoyances associated w/ general dev, none come to mind right now.

**Comment by BrettRToomey** [comment]
Closing this for now.
