### ISSUE TITLE
Feature request: include command-line arguments for HTTP proxy in vapor docker build

### ISSUE THREAD

**Issue by UberJason** [vapor/toolbox#59]
Hi,

I sit behind a corporate firewall and currently I have to go off the corporate network to be able to use `vapor docker build`. Docker actually allows you to supply build-time arguments using `--build-arg <ARG>=<VALUE>`, which is how I would normally supply the HTTP proxy to get through the firewall. Any chance in the future of adding support for command line arguments to `vapor docker build` to allow us to supply those values?

**Comment by tannernelson** [comment]
It should be easy enough to pass the arguments to `vapor docker build` directly to the underlying docker command.

**Comment by BrettRToomey** [comment]
Closing this for now. Please feel free to reopen.

**Comment by UberJason** [comment]
Just wondering, did this feature ever get added? I stopped using the `vapor docker` command all together and manually build my Docker images due to my proxy issue, so I haven't kept up. Would be nice if that feature did get added, though. I won't re-open this issue myself if I was the only person who cared, but if someone else wants this feature and wants to re-open, feel free.

**Comment by vzsg** [comment]
The docker command has been removed altogether.

**Comment by UberJason** [comment]
Oh. Well then. Carry on. 😎
