### ISSUE TITLE
check.qutheory.io is pointing to 0.15.3

### ISSUE THREAD

**Issue by Casperhr** [vapor/toolbox#63]
https://github.com/vapor/toolbox/blob/master/bootstrap.sh 
curl -sL "check.qutheory.io" | bash || exit 1;

is pointing to
https://raw.githubusercontent.com/qutheory/vapor/0.15.3/Utilities/compatibility.sh

I'm not sure where to find that redirect, so created an issue instead

We did a PR to fix the snapshot version

**Comment by tannernelson** [comment]
This has been fixed.
