### ISSUE TITLE
Error: Git already has a heroku remote.

### ISSUE THREAD

**Issue by roma86** [vapor/toolbox#67]
Hello. Can not init heroku app with newly created vapor project via cli.

``` bash
$: vapor new HiVapor
Cloning Template [Done]
$: cd HiVapor
$: ls
Config        Localization  Package.swift Procfile      Public        README.md     Resources     Sources       app.json      license

$: vapor heroku init
Error: Git already has a heroku remote
$: git status
fatal: Not a git repository (or any of the parent directories): .git
```

``` bash
$: vapor version
Vapor Toolbox v0.10.0

$: swiftenv version
DEVELOPMENT-SNAPSHOT-2016-08-18-a (set by /Users/Georg/Develop/VaporTest/HiVapor/.swift-version)
```

**Comment by tannernelson** [comment]
Have you tried deleting the heroku remote that already exists?

**Comment by roma86** [comment]
@tannernelson where it is exist? there are no repository at all. 
Do you see `git status` report output in my example?

**Comment by tannernelson** [comment]
Oh, I see now.

**Comment by LoganWright** [comment]
@roma86 this should have actually failed earlier, it looks like you don't have a git repository. Is that accurate? If so, run `git init` and make sure you're latest changes are committed before running heroku init.

Heroku requires a git repository for the way it builds.

**Comment by roma86** [comment]
@LoganWright thanks for answer.

1. I have tried `vapor new` and then `git init` and then `vapor hero just init` and have the same result.
2. If it so, why `vapor new` does not init new repo for new project?
