### ISSUE TITLE
`vapor xcode` Fails to Generate a Project

### ISSUE THREAD

**Issue by rymcol** [vapor/toolbox#70]
Using 0.10, on macOS 10.12 (16A313a), `vapor xcode` will pull dependencies, but will fail to generate an xcodeproj file afterwards. No errors or feedback are given by the command line tool after failure. 

Additionally, if you attempt to pass a file path to `vapor xcode`, for example `vapor xcode ~/Developer/macOS/project`, this causes the application to print all of the normal console output you would see, but does not pull dependencies or generate the project. This behavior may be related (which I suspect), or it may be another issue altogether. 

Per @LoganWright, I am not the first to mention this, and I am filing this Issue accordingly

**Comment by tannernelson** [comment]
Fixed in #71
