### ISSUE TITLE
Can not stop service in Ubuntu

### ISSUE THREAD

**Issue by Shunzi007** [vapor/toolbox#74]
`vapor run` could start and work well with toolbox v10.0.1. However, after `ctrl + C` to stop, in Ubuntu 16.04, the port (default is 8080) will not be released and the service is still on.

**Comment by Shunzi007** [comment]
Update: use command `sudo lsof -i :8080`, I found another progress is using port 8080, I change Vapor server port to 8181, things go right. Maybe this is a minimum probability incident, not a bug of Vapor.

**Comment by tannernelson** [comment]
You may need to update the toolbox again. We've done various bug fixes to help with this. But even then sometimes the process can go rogue.
