### ISSUE TITLE
Restart device issue

### ISSUE THREAD

**Issue by Shunzi007** [vapor/toolbox#75]
After restart Ubuntu device, things go wrong...

**Comment by Shunzi007** [comment]
update: This is caused by the missing of command `swiftenv`, I should re-initialize `swiftenv` in my bash profile.
I find that the file `$Home/.bashrc` contains nothing about swiftenv.
 After paste 
```
export SWIFTENV_ROOT="$HOME/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$PATH"
eval "$(swiftenv init -)"
if which swiftenv > /dev/null;
then eval "$(swiftenv init -)";
fi
```
into the file, I could recognize command `swiftenv` now.

**Comment by tannernelson** [comment]
This will be a lot easier when Swift 3 is finally out.
