### ISSUE TITLE
Automate build flags

### ISSUE THREAD

**Issue by LoganWright** [vapor/toolbox#76]
Add a simple top level file. `vapor.json` whose contents may be potentially expanded in future, but for now will support `build-flags`. This means that all packages that opt-in can add this file.

After fetch, recursively search Packages/ for additional `vapor.json` files and aggregate.

This allows for custom commands like linking mysql, or a generic build flag the user needs more often. It is also flexible enough that the user can pass whatever they might need to, including customized arguments etc.

Proposed format:

```
"build-flags": {
    "all":  [
        "--customflag"
    ],
    "linux": [
        "--customLinuxLinker",
        "--otherLinker"
    ]
    "macOS": [
        "--custom/linux/linker"
    ]
}
```

**Comment by tannernelson** [comment]
I think relying on the actual build flags to pass into the toolbox could be a little over coupled.

If we had something like this, we wouldn't need to worry about toolbox flags at all. 

```json
{
    "dependencies": {
        "macOS": {
        	"brew": ["mysql"],
        	"link": ["/usr/local/lib"],
        	"include": ["/usr/local/include/mysql"]
        },
        "linux": {
        	"apt": ["mysql-server", "libmysqlclient-dev"]
        }
    }
}
```

**Comment by LoganWright** [comment]
@tannernelson I thought about that, but there's 2 things that make me against specifying type of flag.

1. Less expandable. What if I want custom config flags, or any other thing that a project might want that doesn't fall into these categories. This limits their ability to do customizable fun stuff that doesn't fit into one of these boxes.

2. More work. While there's some slight character savings, I don't think it's worth it. We can have a simple array and pass it in direct w/o any extra effort/testing/support. This requires more testing, more updates, and more explanation to users over "insert flags here and be done with it".

**Comment by tannernelson** [comment]
Okay here's what the MySQL Provider `vapor.json` will look like:

```json
{
    "name": "MySQL Provider",
    "flags": {
        "run": {
            "all": [
                "--config:mysql.version=foo"
            ]
        },
        "build": {
            "macOS": [
                "-Xswiftc",
                "-I/usr/local/include/mysql",
                "-Xlinker",
                "-L/usr/local/lib"
            ],
            "linux": [
                "-Xswiftc",
                "-DNOJSON"
            ]
        },
        "test": {
            "macOS": [
                "-Xswiftc",
                "-I/usr/local/include/mysql",
                "-Xlinker",
                "-L/usr/local/lib"
            ],
            "linux": [
                "-Xswiftc",
                "-DNOJSON"
            ]
        }
    }
}
```

**Comment by HazAT** [comment]
I've just wanted to clear that up since this cost me a few hours.
For me `macOS` wasn't the right key, it is just `mac` then all the parameters work as described.
https://github.com/vapor/toolbox/issues/181
